package com.idea3d.juegoparaparejas

data class QuestionItem(val question: String, val answers: List<String>)

data class QuestionPack(val id: Int, val questions: List<QuestionItem>) {
    fun questionAt(index: Int): QuestionItem = questions[index]
    val size: Int get() = questions.size
}

object QuestionBank {
    val packs: Map<Int, QuestionPack> = mapOf(
        1 to QuestionPack(1, listOf(
            QuestionItem("Tu estación favorita es...", listOf("OTOÑO", "INVIERNO", "PRIMAVERA", "VERANO")),
            QuestionItem("Si tu vida fuera un video juego ¿de que tipo sería?", listOf("Acción", "Aventura", "Deportes", "Fiesta")),
            QuestionItem("¿Cual es tu tipo de música preferida?", listOf("Pop", "Rock", "Reggaeton", "Electrónica")),
            QuestionItem("¿A qué animal te pareces más?", listOf("Perro", "Gato", "León", "Tortuga")),
            QuestionItem("Es viernes en la noche y tú...", listOf("¡De fiesta!", "Trabajando...", "Durmiendo", "viendo series o películas")),
            QuestionItem("Si tuvieras un deseo ¿Cual sería?", listOf("Ser el mejor en todo", "Superpoderes", "Dinero ¡y mucho!", "Dominar el mundo")),
            QuestionItem("En qué época debiste haber nacido", listOf("La edad oscura", "Los 60s", "La actualidad", "El futuro")),
            QuestionItem("¿Qué te haría más feliz?", listOf("Dormir más", "Menos trabajo", "Más tiempo con amigos y familia", "Más dinero")),
            QuestionItem("Describe tu estilo en una palabra", listOf("Fino", "Glamuroso", "Elegante", "Hipster")),
            QuestionItem("¿Que buscas más en un amigo?", listOf("Lealtad", "Amabilidad", "Humor", "Inteligencia")),
            QuestionItem("Tu color favorito es...", listOf("Verde", "Rojo/Rosa", "Azul/Violeta", "Amarillo")),
            QuestionItem("¿Cual es tu tipo de película favorita", listOf("Acción", "Comedia", "Romance", "Ciencia Ficción")),
        )),
        2 to QuestionPack(2, listOf(
            QuestionItem("¿Cuál es tu deporte favorito", listOf("Béisbol", "Fútbol", "Basket", "Tennis")),
            QuestionItem("¿Cuál es la cosa más importante en tu vida", listOf("Familia", "Amigos", "Trabajo", "Pasatiempos")),
            QuestionItem("¿Cual es tu bebida favorita?", listOf("Agua", "Café/Té", "Gaseosa", "Alcohol")),
            QuestionItem("¿A qué le tienes más miedo?", listOf("Insectos", "Alturas", "Encierro", "Fracaso")),
            QuestionItem("¿Qué prefieres para el desayuno?", listOf("Tostadas", "Cereal", "Huevos", "Sólo un café")),
            QuestionItem("¿A donde irías en un día libre?", listOf("El campo", "La ciudad", "La playa", "Me quedaría en casa")),
            QuestionItem("¿Cual es tu momento favorito del día", listOf("La mañana", "La tarde", "La noche", "La madrugada")),
            QuestionItem("¿Qué llevas siempre en tu bolso de viaje?", listOf("Un cargador de teléfono", "Dinero extra", "Una guía de viaje", "Un cepillo de dientes")),
            QuestionItem("Qué superpoder te gustaría tener", listOf("Superfuerza", "Ser invisible", "Detener el tiempo", "Volar")),
            QuestionItem("¿Que te gustaría ser?", listOf("Un músico famoso", "Un atleta de élite", "Un político respetado", "Un gran profesional")),
            QuestionItem("Si sólo quedarán dos horas para el fin del mundo ¿Qué harías?", listOf("Dormir", "Buscar una buena vista", "Cualquier locura que se me ocurra", "Decirle adiós a mis seres queridos")),
            QuestionItem("¿Qué preferirías recibir cómo regalo", listOf("Chocolates", "Libros", "Flores", "Alcohol")),
        )),
        3 to QuestionPack(3, listOf(
            QuestionItem("¿Qué te llevarías a una isla desierta", listOf("Un libro", "Una radio", "Un cuchillo", "Un balón")),
            QuestionItem("¿Qué prefieres cómo tema de conversación?", listOf("Deportes", "Música", "Películas y series", "Política")),
            QuestionItem("¿Qué prefieres hacer un fin de semana?", listOf("Pescar", "Escalar montañas", "Broncearte", "Ir a conciertos")),
            QuestionItem("Una película sobre tu vida ¿Qué tipo de película sería?", listOf("Una comedia", "Un drama", "De Acción", "Romántica")),
            QuestionItem("¿Cuál de tus sentidos te gustaría mejorar?", listOf("Vista", "Audición", "Olfato", "Gusto")),
            QuestionItem("¿Qué adjetivo te define mejor?", listOf("Infantil", "Alegre", "Sociable", "Trabajador")),
            QuestionItem("A qué lección preferirías inscribirte?", listOf("Tiro con arco", "Cerámica", "Esgrima", "Baile")),
            QuestionItem("¿Sin qué no podrías vivir?", listOf("Música", "Teléfono móvil", "Mi mascota", "Agua caliente")),
            QuestionItem("¿Qué harías si ganaras la loteria", listOf("Comprar un coche nuevo", "Invertir el dinero", "Comprar una casa", "Ayudar a los necesitados")),
            QuestionItem("Qué harías con 2 horas de tiempo libre", listOf("Dormir", "Estudiar", "Entrar en mis redes sociales", "Jugar videojuegos")),
            QuestionItem("¿Qué animal preferirías cómo mascota?", listOf("Perro", "Gato", "Serpiente", "Caballo")),
            QuestionItem("Cuál es el sueño de tu vida?", listOf("Ser millonario", "Ser famoso", "Tener muchos hijos", "Viajar por el mundo")),
        )),
        4 to QuestionPack(4, listOf(
            QuestionItem("¿Qué te atrae más?", listOf("Dinero", "Familia", "Estabilidad", "Aventura")),
            QuestionItem("¿Qué preferirías ser?", listOf("Más fuerte", "Más alto", "Más bajo", "Más delgado")),
            QuestionItem("¿Qué papel te gustaría en una obra de teatro?", listOf("El héroe", "El amigo del héroe", "El villano", "Un árbol")),
            QuestionItem("A que preferirías poner fin?", listOf("La Guerra", "El hambre", "Enfermedades", "Contaminación")),
            QuestionItem("¿Qué actividad prefieres", listOf("Jugar un videojuego", "Ver la televisión", "Hacer ejercicio", "Jugar un juego de mesa")),
            QuestionItem("¿Qué prefieres ver en la televisión?", listOf("Deportes", "Noticias", "Documentales", "Reality Shows")),
            QuestionItem("Dondes prefieres pasar tus vacaciones", listOf("En el caribe", "En las montañas", "En una gran ciudad", "En un safarí")),
            QuestionItem("Cual es tu medio de transporte favorito", listOf("Tren", "Barco", "Coche", "Avión")),
            QuestionItem("¿Qué tan inteligente eres?", listOf("Brillante", "Casi un genio", "Promedio", "Algo Tonto")),
            QuestionItem("¿Cuál es tu asignatura favorita?", listOf("Matemática", "Ciencia", "Educación Física", "Arte")),
            QuestionItem("Cuando es tu cumpleaños?", listOf("Verano", "Otoño", "Primavera", "Invierno")),
            QuestionItem("¿Cuál es tu animal favorito?", listOf("Perro", "Gato", "Caballo", "Conejo")),
        )),
        5 to QuestionPack(5, listOf(
            QuestionItem("¿Cuál es tu elemento favorito?", listOf("Fuego", "Aire", "Tierra", "Agua")),
            QuestionItem("¿Cuando eres más productivo?", listOf("Mañana", "Tarde", "Noche", "Madrugada")),
            QuestionItem("¿Quién eres en tu grupo de amigos?", listOf("El lider", "El chistoso", "El creativo", "El Leal")),
            QuestionItem("¿Cuál es tu fecha favorita?", listOf("Navidad", "Pascuas", "San Valentin", "Halloween")),
            QuestionItem("¿Cuál es el trabajo de tus sueños?", listOf("Médico", "Músico", "Atleta", "Astronauta")),
            QuestionItem("¿En qué desearías ser mejor?", listOf("Matemáticas", "Canto", "Oratoria", "Deportes")),
            QuestionItem("¿De qué te gustaría tener un año de suministro?", listOf("Cereal", "Helado", "Donas", "Chocolate")),
            QuestionItem("¿Qué actividad preferirías intentar? ", listOf("Ir a un safarí", "Tirarte en paracaídas", "Escalar un volcán", "Nadar con delfines")),
            QuestionItem("¿Cual es tu atividad favorita alrededor de una fogata?", listOf("Cantar", "Contar historias de terror", "Asar malvaviscos", "Jugar charadas")),
            QuestionItem("¿Qué te gusta más de la navidad?", listOf("Estar con tu familia", "La fiesta", "Comer y beber", "Los regalos")),
            QuestionItem("¿Que prefieres jugar?", listOf("Videojuegos", "Juegos de mesa", "Cartas", "Deportes")),
            QuestionItem("¿Cómo sería tu salida nocturna ideal?", listOf("Ver un partido de fútbol", "Ir al teatro", "Ir a un concierto", "Ir a un club")),
        )),
        6 to QuestionPack(6, listOf(
            QuestionItem("¿Qué habilidad extraordinria te gustaría tener?", listOf("Volar", "Respirar bajo el agua", "Caminar por las paredes", "Visión de rayos X")),
            QuestionItem("¿A quién te gustaría tener de amigo?", listOf("Mi estrella de cine favorita", "Mi músico favorito", "Mi deportista favorito", "Mi político favorito")),
            QuestionItem("¿Qué papel te gustaría en una película?", listOf("Un apuesto héroe", "Un maligno villano", "El creativo que se roba la escena", "El mejor amigo del héroe")),
            QuestionItem("¿Cómo serían tus vacaciones ideales?", listOf("De relax en la playa", "En una gran ciudad con muchos museos", "De fiesta en fiesta", "De senderismo en las montañas")),
            QuestionItem("¿Cuál de estos países te gustaría visitar más?", listOf("Perú", "Japón", "Francia", "EEUU")),
            QuestionItem("Cuál es tu red social favorita?", listOf("Instagram", "Tik Tok", "Twitter", "Facebook")),
            QuestionItem("¿Qué tipo de bocadillo prefieres?", listOf("Chocolate", "Patatas fritas", "Galletas", "Fruta")),
            QuestionItem("¿Qué harías si fueras invisible? ", listOf("Hacer bromas", "Robar dinero", "Espiar a la gente", "Hacer buenas cosas para el mundo")),
            QuestionItem("Si tuvieras que contratar a alguien ¿A qué cualidad le darías mayor valor?", listOf("Apariencia", "Experiencia", "Educación", "Carisma")),
            QuestionItem("¿Qué situación sería la peor para ti?", listOf("Apocalipsis Zombie", "Rebelión de las máquinas", "Invasión extraterrestre", "Una gran inundación")),
            QuestionItem("¿Cómo sería tu domingo perfecto?", listOf("Jugar juegos de mesa", "Un viaje por la carretera", "Beber en bares", "Una gran fiesta")),
            QuestionItem("¿Qué haces para relajarte?", listOf("Tomar sol en el jardín", "Tirarme en el sofá", "Beber con amigos", "Jugar videojuegos")),
        )),
        7 to QuestionPack(7, listOf(
            QuestionItem("¿Cuál es tu comida favorita?", listOf("Sushi", "Pasta", "Pizza", "Hamburguesas")),
            QuestionItem("¿Que ambiente natural es tu favorito?", listOf("El bosque", "Montañas nevadas", "La playa", "Un lago y montañas")),
            QuestionItem("¿Qué te motiva más?", listOf("El éxito", "La familia", "El poder", "La competencia")),
            QuestionItem("¿Que instrumento te gustaría poder tocar a la perfección?", listOf("Guitarra", "Bajo", "Bateria", "Piano")),
            QuestionItem("¿Cuál es tu día favorito de la semana?", listOf("Sábado", "Domingo", "Viernes", "Otro")),
            QuestionItem("Cuál es tu comida favorita?", listOf("Desayuno", "Almuerzo", "Merienda", "Cena")),
            QuestionItem("¿Qué género de tv en tu favorito?", listOf("Drama", "Comedia", "Crimen", "Deporte")),
            QuestionItem("¿Cuál crees que es tu cualidad más atractiva?", listOf("Apariencia", "Inteligencia", "Ambición", "Humor")),
            QuestionItem("¿Qué deberías mejorar?", listOf("Tu dieta", "Carrera profesional", "Finanzas", "Cultura")),
            QuestionItem("¿Qué superhéroe te gustaría ser?", listOf("Batman", "Superman", "Spiderman", "La mujer maravilla")),
            QuestionItem("¿Cómo sería tu primera cita perfecta?", listOf("Cenar en casa", "Bailar y beber en un club", "Ir a un concierto", "Ir al cine")),
            QuestionItem("¿Qué tan seguido haces ejercicio?", listOf("Todos los días", "5 veces a la semana", "2 o 3 veces por semana", "Una vez o nunca")),
        )),
        8 to QuestionPack(8, listOf(
            QuestionItem("¿Cómo prefieres pasar una hora de tiempo libre?", listOf("Yendo de compras", "Durmiendo", "En el gimnasio", "Viendo TV")),
            QuestionItem("¿A quién elegirías para cambiar de vida por un año?", listOf("Tu jefe", "Tu hermano o hermana", "Un amigo", "Tu pareja")),
            QuestionItem("Por lo general ¿Qué sueles usar más a menudo?", listOf("El corazón", "La lógica", "El dinero", "La experiencia")),
            QuestionItem("¿Que te daría mayor felicidad?", listOf("Viajar por el mundo", "Hacer más amigos", "Tener más dinero", "Estar en mejor forma")),
            QuestionItem("¿Cuál es tu mayor prioridad ahora mismo?", listOf("Relación sentimental", "Carrera profesional", "Reputación", "Éxito")),
            QuestionItem("Cuál es tu miedo más grande?", listOf("La muerte", "Estar solo", "Los bichos", "Espacios pequeños")),
            QuestionItem("¿Cómo calificarías tu forma de bailar?", listOf("Desastrosa", "Mala", "Promedio", "Genial")),
            QuestionItem("¿Qué te gustaría más?", listOf("Ser más alto", "Ser más delgado", "Ser más jóven", "Ser más bajo")),
            QuestionItem("¿Qué preferirías hacer?", listOf("Manejar un moto de agua", "Bucear", "Saltar en paracaídas", "Pilotear un avión")),
            QuestionItem("¿Cómo calificarías tu forma de cantar?", listOf("Excelente", "Promedio", "Mala", "Desastrosa")),
            QuestionItem("¿Qué priorizas en tus vacaciones?", listOf("La comida", "El alojamiento", "Espectáculos", "La compania")),
            QuestionItem("¿En qué eres peor?", listOf("Bailando", "Cantando", "Dibujando", "Deportes")),
        )),
        9 to QuestionPack(9, listOf(
            QuestionItem("¿Qué preferirías tener en tu casa?", listOf("Una sala de juegos", "Un gimnasio", "Un estudio", "Una piscina")),
            QuestionItem("¿Cómo calificarías tu puntualidad?", listOf("Excelente", "Buena", "Promedio", "Muy mala")),
            QuestionItem("¿Cómo serían unas vaciones de pesadilla?", listOf("Caminando mucho", "En un campamento", "En la playa", "En una ciudad")),
            QuestionItem("¿Cuál es tu género literario favorito?", listOf("Romance", "Crimen", "Historia", "Biográficos")),
            QuestionItem("¿Qué empleo se ajusta mejor a tu perfil?", listOf("Doctor", "Maestro", "Abogado", "Vendedor")),
            QuestionItem("¿Cómo eres en la cocina?", listOf("Todo un chef", "Nada mal", "Todo se quema", "No cocinas")),
            QuestionItem("Elige una de las siguientes mascotas", listOf("Una cobra", "Un chimpancé", "Un hámster", "Un elefante")),
            QuestionItem("¿Qué monumento te gustaría visitar?", listOf("La estatua de la libertad", "La gran muralla china", "La torre Eiffel", "Las pirámides de Egipto")),
            QuestionItem("¿Qué utilizas más a menudo?", listOf("Netflix", "Amazon Prime", "Disney+", "Youtube")),
            QuestionItem("¿Qué tipo de clima prefieres?", listOf("Soleado", "Lluvioso", "Nevado", "Ventoso")),
            QuestionItem("¿Qué prefieres para tarjeta de regalo?", listOf("Comida", "Viajes", "Cosméticos", "Videojuegos")),
            QuestionItem("¿Cuál piensas que es tu mayor fortaleza?", listOf("Buen humor", "Lealtad", "Ambición", "Calidez")),
        )),
        10 to QuestionPack(10, listOf(
            QuestionItem("Tienes que renunciar a una cosa por todo un mes ¿Cuál sería?", listOf("Teléfono móvil", "Redes sociales", "Videojuegos", "Chocolate")),
            QuestionItem("¿Cuál es tu mayor preocupación?", listOf("Salud", "Trabajo", "Dinero", "Familia")),
            QuestionItem("¿En donde disfrutas más?", listOf("En una boda", "En un cumpleaños", "En Navidad", "En Año Nuevo")),
            QuestionItem("¿Cuántos libros lees al mes?", listOf("0", "1", "2", "Más de tres")),
            QuestionItem("Si te hicieran una fiesta ¿Qué sentirías?", listOf("Emoción", "Agradecimiento", "Verguenza", "Euforia")),
            QuestionItem("¿Qué preferirías tener en tu casa?", listOf("Un trampolín", "Una piscina olímpica", "Una casita del árbol", "Una cancja de tennis")),
            QuestionItem("¿Quién es la primera persona a la que cuentas una buena noticia?", listOf("Tus padres", "Tu mejor amigo", "Tu pareja", "Tu hermano")),
            QuestionItem("¿Qué extravías más a menudo?", listOf("Teléfono móvil", "Cartera", "Anteojos", "Llaves")),
            QuestionItem("¿Qué te parece más divertido?", listOf("Una caminata tranquila", "Salir a bailar", "Tomar un café con un amigo", "Hacer deportes")),
            QuestionItem("¿Qúe factor es más importante a la hora de comprar algo?", listOf("La calidad", "El precio", "La moda", "Lo práctico")),
            QuestionItem("¿Cuál de las siguientes cosas ansías más?", listOf("Conocimientos", "Dinero", "Comida", "Tiempo de relax")),
            QuestionItem("Si tuvieras que dedicar tiempo a una sola de estas cosas por el resto de tu vida ¿Cuál eliges?", listOf("Familia", "Amigos", "Trabajo", "Pasatiempos")),
        )),
        11 to QuestionPack(11, listOf(
            QuestionItem("¿Con cuántas personas tuviste sexo?", listOf("1-3", "3-10", "10-20", "20+")),
            QuestionItem("¿Jugaste Strip Poker alguna vez?", listOf("Sí y lo volvería a hacer", "No pero quiero hacerlo", "Si pero no quiero que se repita", "No lo haría jamás")),
            QuestionItem("¿Cual es el lugar más incómodo donde lo has hecho?", listOf("En un baño", "En la playa", "En un auto", "En la calle")),
            QuestionItem("Si te proponen grabar un video xxx, tú:", listOf("Te enojas", "Te excitas", "Te ríes", "Te averguenzas")),
            QuestionItem("Si sólo pudieras tocarme en una parte del cuerpo ¿Cuál sería?", listOf("La cara", "El pecho", "Las piernas", "Partes íntimas")),
            QuestionItem("¿Cuánto tiempo has estado sin acostarte con nadie?", listOf("Una semana", "Un mes", "Seis meses", "Más de un año")),
            QuestionItem("¿Harías un trío?", listOf("Sí, con otra chica", "Sí, con otro chico", "No ahora, quizás más adelante", "Jamás")),
            QuestionItem("¿Qué es lo que más te excita?", listOf("Un buen cuerpo", "La inteligencia", "El atrevimiento", "La bondad")),
            QuestionItem("¿Qué te parece más divertido?", listOf("Una caminata tranquila", "Salir a bailar", "Tomar un café con un amigo", "Hacer deportes")),
            QuestionItem("¿A qué todavía no te animas?", listOf("Sadomasoquismo", "Sexo anal", "Un trío", "Disfraces")),
            QuestionItem("¿En que lugar público te gustaría hacerlo?", listOf("Calle", "Una plaza", "La playa", "Un bosque")),
            QuestionItem("¿Alguna vez tuviste un sueño erótico con alguna persona que no debías?", listOf("Un amigo/a", "Un/a familiar", "Un/a compañero/a", "Nunca")),
        )),
        12 to QuestionPack(12, listOf(
            QuestionItem("¿Cuál fue el máximo de personas con las que has tenido sexo al mismo tiempo?", listOf("Nunca con más de una", "Dos", "Tres", "Más de tres")),
            QuestionItem("¿Cuánto tiempo puedes estar haciendólo sin parar?", listOf("Cinco minutos", "Treinta minutos", "Una hora", "Más de dos horas")),
            QuestionItem("¿Alguna vez estuviste en un club swingers?", listOf("Sí y volvería a hacerlo", "Sí pero no me gustó", "No pero me da curiosidad", "Jamás lo haría")),
            QuestionItem("¿Qué personaje ficticio te consideras debajo de las sábanas?", listOf("Ironman", "La mujer maravilla", "La bella durmiente", "Drácula")),
            QuestionItem("¿Cómo te gusta que te hagan sexo oral?", listOf("Con cariño", "Bien guarro", "Extremo", "No me gusta")),
            QuestionItem("¿Qué es lo más lejos a lo que has llegado en una primera cita?", listOf("Un beso francés", "Sexo oral", "Sexo tradicional", "Sexo con otras personas")),
            QuestionItem("¿Cual es tu especialidad?", listOf("Los disfraces", "Los juguetes", "La previa y el sexo oral", "Tu forma de moverte en la cama")),
            QuestionItem("Si se vienen en tu boca, tú:", listOf("Escupes", "Tragas", "Pides más", "Te enojas")),
            QuestionItem("¿De qué parte de tu cuerpo estás más orgulloso/a?", listOf("Tu carita", "Tu colita", "Tu pecho", "Tu cosita")),
            QuestionItem("¿Qué es lo más embarazoso que te ha pasado estando con alguien?", listOf("No funcionó el amigo", "Alguien se vino demasiado rápido", "Nos encontraron", "Hubiera sido mejor tener un inodoro cerca")),
            QuestionItem("¿Alguna fantasia que no hayas cumplido?", listOf("En un avión", "En un lugar público", "En un auto en movimiento", "Juego de roles con disfraces")),
            QuestionItem("¿Con qué frecuencia te gusta tener sexo?", listOf("Todos los días", "Día por medio", "Una vez por semana", "Una vez al mes")),
        )),
        13 to QuestionPack(13, listOf(
            QuestionItem("¿Qué posición te gusta más?", listOf("Misionero", "De perrito", "A cococho", "Boca abajo")),
            QuestionItem("¿Cual es tu manera de seducir?", listOf("Halagando a la otra persona", "Hablando de tus proezas", "Haciendo reir a la otra persona", "Con una mirada penetrante")),
            QuestionItem("¿Te has acostado con una ex pareja después de cortar?", listOf("Sí, al poco tiempo", "Sí, un reencuentro por los viejos tiempos", "No pero nos hemos contactado", "Jamás lo haría")),
            QuestionItem("¿Que clase de juguetes te gusta?", listOf("Animalitos", "Collares", "Cosas que me hagan doler y vibrar", "Ninguna")),
            QuestionItem("¿Qué clase de disfraz es tu favorito?", listOf("Policia", "Anime", "Colegiala", "Superhéroes")),
            QuestionItem("¿Cómo te gustaría que se vistiera tu pareja para dormir contigo?", listOf("Encaje", "Camiseta larga", "Desnuda", "Pijama")),
            QuestionItem("¿Te gustaría que te aten?", listOf("Con una soga", "Con esposas", "Con sogas y vendas en los ojos", "No me gustaría")),
            QuestionItem("Si se vienen en tu boca, tú:", listOf("Escupes", "Tragas", "Pides más", "Te enojas")),
            QuestionItem("¿Qué es lo más atrevido que has hecho en un cine?", listOf("Un beso", "Dedos mojados", "Sexo oral", "Sexo en lo alto de la sala")),
            QuestionItem("¿A qué edad perdiste la virginidad?", listOf("13-15", "16-18", "18-22", "22+")),
            QuestionItem("¿Que es lo más sucio que has pensado hacer con tu pareja?", listOf("Sexo anal", "Un trío", "Intercambio de parejas", "Una orgía")),
            QuestionItem("¿Alguna vez te has masturbado en un baño público?", listOf("En el trabajo", "En la escuela", "En una estación de servicio", "Nunca")),
        )),
        14 to QuestionPack(14, listOf(
            QuestionItem("¿Con qué frecuencia te masturbas?", listOf("Todos los días", "Cada dos o tres días", "Una vez por semana", "Una vez al mes")),
            QuestionItem("¿Qué actitud te gusta que tenga tu pareja en la cama?", listOf("Dominante", "Pasiva", "Sumisa", "Violenta")),
            QuestionItem("¿Cuál es el máximo de orgasmos que has tenido en la misma noche?", listOf("Apenas uno", "Entre dos y tres", "Entre cuatro y seis", "Más de siete")),
            QuestionItem("¿En cuánto llegas al orgasmo en promedio?", listOf("Cuestión de segundos", "Cinco minutos", "Veinte minutos", "Una hora")),
            QuestionItem("¿Donde te gustaría recibir un masaje?", listOf("Cuello", "Espalda", "Cola", "Pies")),
            QuestionItem("¿Qué opinas de los chupones?", listOf("Es infantil", "Marco mi territorio", "Me dan verguenza", "Los llevo con orgullo")),
            QuestionItem("¿Que es lo más salvaje que has hecho?", listOf("Romper un condón", "Romper una cama", "Sangrar por hacerlo tan fuerte", "Dar una nalgada muy dolorosa")),
            QuestionItem("¿Cuál es tu fetiche?", listOf("Sexo con los pies", "Pegarle a tu pareja ", "Escupir durante el sexo oral", "Otro bastante raro")),
            QuestionItem("¿Qué pasa cuando hay conocidos en el cuarto de al lado?", listOf("Se folla más fuerte", "Se grita sin pudor", "Se trata de guardar el mayor silencio posible", "No se hace nada por respeto")),
            QuestionItem("¿Qué parte del cuerpo de tu pareja te gusta chupar?", listOf("El cuello", "Los pies", "Los pechos", "Sus partes íntimas")),
            QuestionItem("¿Cómo crees que la pasarías en una orgía?", listOf("¡Genial!", "Me daría verguenza", "Depende de cómo la pase mi pareja", "Nunca iría a una orgía y menos con mi amor")),
            QuestionItem("¿Tuviste relaciones de una noche?", listOf("Una vez", "Más de tres veces", "Más de diez veces", "Nunca")),
        )),
        15 to QuestionPack(15, listOf(
            QuestionItem("¿En donde te gusta más tener sexo?", listOf("En la cama", "En el sillón", "En el baño", "Sobre la mesa o el lavarropas")),
            QuestionItem("¿Venderías nudes?¿A qué precio?", listOf("Mil dólares", "Diez mil dólares ", "Cien mil dólares o más", "No vendería")),
            QuestionItem("¿Por qué precio dejarías que un desconocido haga lo que quiera contigo?", listOf("Diez mil dólares", "Cien mil dólares", "Un millón o más", "Mi dignidad no tiene precio")),
            QuestionItem("¿Recuerdas la primera vez que te sentiste excitado/a?", listOf("A los 12", "A los 13", "A los 14", "A los 15")),
            QuestionItem("¿Donde te gustaría recibir un masaje?", listOf("Cuello", "Espalda", "Cola", "Pies")),
            QuestionItem("¿Qué te gustaría que te hagan mientras conduces?", listOf("Una manualidad", "Una mamada", "Que te digan cosas excitantes", "Nada, es peligroso")),
            QuestionItem("¿Que es lo más grosero que has dicho follando?", listOf("Eres mi puta", "Quiero ser tu perrita", "Quiero tu leche", "Más duro Arturo")),
            QuestionItem("¿Cómo sería tu noche en pareja ideal?", listOf("Con velas y pétalos de rosas", "Follando bien duro sin parar", "Viendo películas y teniendo sexo de vez en cuando", "Adoptando roles para toda la noche")),
            QuestionItem("¿Qué piensas de las relaciones abiertas?", listOf("No es para mi", "Me gustaría probar", "Me da curiosidad", "Me moriría de celos")),
            QuestionItem("¿Cuando fue la última vez que tuviste un sueño sexual intenso?", listOf("Esta semana", "El mes pasado", "Este año", "Ya ni lo recuerdo")),
            QuestionItem("¿Cuánto tiempo crees que podrías estar sin follar?", listOf("Un día", "Una semana", "Un mes", "Un año")),
            QuestionItem("¿Cuál es el mejor momento del día para hacer el amor?", listOf("A la mañana", "A la tarde", "A la noche", "A la madrugada")),
        )),
        16 to QuestionPack(16, listOf(
            QuestionItem("¿Qué agujero te da más placer?", listOf("La boca", "La vagina", "El ano", "Las manos o pies al masturbar")),
            QuestionItem("¿Antes de estar en pareja tuviste sexo prohibido?¿Con quién?", listOf("Un amigo o amiga", "Un o una familiar", "Un/a compañero/a de trabajo", "Nunca")),
            QuestionItem("¿Con cuál de estos tienes alguna fantasía?", listOf("Un o una policía", "Un sacerdote o monja", "Un/a médico/a", "Otros")),
            QuestionItem("¿Quién es tu permitido sexual?", listOf("Un músico o música", "Actor o actriz de cine", "Un/a político/a que admiras ", "Un/a atleta de élite")),
            QuestionItem("¿Alguna vez comiste mientras follabas?", listOf("Fresas", "Chocolate", "Sushi", "Nunca lo hice, lo hacemos la próxima vez")),
            QuestionItem("¿Cuántas veces tienes que follar con una persona para contarle lo que te gusta?", listOf("A la primera", "Dos o tres veces", "Cuatro a siete veces", "Necesito una relación larga para entrar en confianza")),
            QuestionItem("Cual es la mayor cantidad de veces seguidas que lo has hecho", listOf("Dos", "Tres", "Cuatro", "Cinco o más")),
            QuestionItem("¿Luces prendidas o apagadas?", listOf("Prendidas, que se vea TODO", "Apagadas, me da verguenza", "Tenues, como la luz de las velas", "Luces de colores cómo si fuera un show")),
            QuestionItem("¿Qué prefieres entre estas opciones?", listOf("Lamer", "Morder", "Masajear", "Escupir")),
            QuestionItem("¿Has enviado fotos de alguna de estas partes de tu cuerpo?", listOf("Cola", "Pechos", "Partes íntimas", "Todas las anteriores")),
            QuestionItem("¿Te gusta la lectura erótica?", listOf("Sólo un mensaje de vez en cuando", "Me gusta que mi pareja me excite con mensajes siempre que no la puedo ver", "Leo novelas enteras", "No me gusta")),
            QuestionItem("¿Qué tipo de porno te gusta más?", listOf("Amateur", "Interracial", "Orgías", "Sadomasoquismo")),
        )),
    )

    fun getPack(id: Int): QuestionPack = packs[id] ?: error("Unknown pack id: $id")
}
