#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generates localized string resources and updated QuestionBank.kt for all 16 packs.
"""

import os, textwrap

BASE = "/Users/nestor/Juego-para-parejas/app/src/main/res"

# ─── DATA ────────────────────────────────────────────────────────────────────
# Format: { pack_id: [ (question_es, question_en, question_pt,
#                        [ans_es, ans_en, ans_pt], [ans_es, ans_en, ans_pt], ...) ] }

PACKS = {
1: [
  ("Tu estación favorita es...",
   "Your favorite season is...",
   "Sua estação favorita é...",
   ("OTOÑO","AUTUMN","OUTONO"),
   ("INVIERNO","WINTER","INVERNO"),
   ("PRIMAVERA","SPRING","PRIMAVERA"),
   ("VERANO","SUMMER","VERÃO")),
  ("Si tu vida fuera un video juego ¿de que tipo sería?",
   "If your life were a video game, what type would it be?",
   "Se sua vida fosse um videogame, que tipo seria?",
   ("Acción","Action","Ação"),
   ("Aventura","Adventure","Aventura"),
   ("Deportes","Sports","Esportes"),
   ("Fiesta","Party","Festa")),
  ("¿Cual es tu tipo de música preferida?",
   "What is your favorite type of music?",
   "Qual é seu tipo de música favorito?",
   ("Pop","Pop","Pop"),
   ("Rock","Rock","Rock"),
   ("Reggaeton","Reggaeton","Reggaeton"),
   ("Electrónica","Electronic","Eletrônica")),
  ("¿A qué animal te pareces más?",
   "Which animal are you most like?",
   "A qual animal você mais se parece?",
   ("Perro","Dog","Cachorro"),
   ("Gato","Cat","Gato"),
   ("León","Lion","Leão"),
   ("Tortuga","Turtle","Tartaruga")),
  ("Es viernes en la noche y tú...",
   "It's Friday night and you...",
   "É sexta à noite e você...",
   ("¡De fiesta!","Partying!","Na festa!"),
   ("Trabajando...","Working...","Trabalhando..."),
   ("Durmiendo","Sleeping","Dormindo"),
   ("viendo series o películas","Watching series or movies","Assistindo séries ou filmes")),
  ("Si tuvieras un deseo ¿Cual sería?",
   "If you had one wish, what would it be?",
   "Se você tivesse um desejo, qual seria?",
   ("Ser el mejor en todo","Be the best at everything","Ser o melhor em tudo"),
   ("Superpoderes","Superpowers","Superpoderes"),
   ("Dinero ¡y mucho!","Money, lots of it!","Dinheiro, muito!"),
   ("Dominar el mundo","World domination","Dominar o mundo")),
  ("En qué época debiste haber nacido",
   "What era should you have been born in?",
   "Em que época você deveria ter nascido?",
   ("La edad oscura","The Dark Ages","A Idade das Trevas"),
   ("Los 60s","The 60s","Os anos 60"),
   ("La actualidad","The present","A atualidade"),
   ("El futuro","The future","O futuro")),
  ("¿Qué te haría más feliz?",
   "What would make you happiest?",
   "O que te deixaria mais feliz?",
   ("Dormir más","More sleep","Dormir mais"),
   ("Menos trabajo","Less work","Menos trabalho"),
   ("Más tiempo con amigos y familia","More time with friends and family","Mais tempo com amigos e família"),
   ("Más dinero","More money","Mais dinheiro")),
  ("Describe tu estilo en una palabra",
   "Describe your style in one word",
   "Descreva seu estilo em uma palavra",
   ("Fino","Refined","Refinado"),
   ("Glamuroso","Glamorous","Glamoroso"),
   ("Elegante","Elegant","Elegante"),
   ("Hipster","Hipster","Hipster")),
  ("¿Que buscas más en un amigo?",
   "What do you value most in a friend?",
   "O que você mais valoriza em um amigo?",
   ("Lealtad","Loyalty","Lealdade"),
   ("Amabilidad","Kindness","Gentileza"),
   ("Humor","Humor","Humor"),
   ("Inteligencia","Intelligence","Inteligência")),
  ("Tu color favorito es...",
   "Your favorite color is...",
   "Sua cor favorita é...",
   ("Verde","Green","Verde"),
   ("Rojo/Rosa","Red/Pink","Vermelho/Rosa"),
   ("Azul/Violeta","Blue/Purple","Azul/Violeta"),
   ("Amarillo","Yellow","Amarelo")),
  ("¿Cual es tu tipo de película favorita",
   "What is your favorite type of movie?",
   "Qual é seu tipo favorito de filme?",
   ("Acción","Action","Ação"),
   ("Comedia","Comedy","Comédia"),
   ("Romance","Romance","Romance"),
   ("Ciencia Ficción","Sci-Fi","Ficção Científica")),
],
2: [
  ("¿Cuál es tu deporte favorito",
   "What is your favorite sport?",
   "Qual é seu esporte favorito?",
   ("Béisbol","Baseball","Beisebol"),
   ("Fútbol","Soccer","Futebol"),
   ("Basket","Basketball","Basquete"),
   ("Tennis","Tennis","Tênis")),
  ("¿Cuál es la cosa más importante en tu vida",
   "What is the most important thing in your life?",
   "Qual é a coisa mais importante na sua vida?",
   ("Familia","Family","Família"),
   ("Amigos","Friends","Amigos"),
   ("Trabajo","Work","Trabalho"),
   ("Pasatiempos","Hobbies","Hobbies")),
  ("¿Cual es tu bebida favorita?",
   "What is your favorite drink?",
   "Qual é sua bebida favorita?",
   ("Agua","Water","Água"),
   ("Café/Té","Coffee/Tea","Café/Chá"),
   ("Gaseosa","Soda","Refrigerante"),
   ("Alcohol","Alcohol","Álcool")),
  ("¿A qué le tienes más miedo?",
   "What are you most afraid of?",
   "Do que você tem mais medo?",
   ("Insectos","Insects","Insetos"),
   ("Alturas","Heights","Alturas"),
   ("Encierro","Enclosed spaces","Espaços fechados"),
   ("Fracaso","Failure","Fracasso")),
  ("¿Qué prefieres para el desayuno?",
   "What do you prefer for breakfast?",
   "O que você prefere no café da manhã?",
   ("Tostadas","Toast","Torradas"),
   ("Cereal","Cereal","Cereal"),
   ("Huevos","Eggs","Ovos"),
   ("Sólo un café","Just a coffee","Só um café")),
  ("¿A donde irías en un día libre?",
   "Where would you go on a free day?",
   "Onde você iria em um dia livre?",
   ("El campo","The countryside","O campo"),
   ("La ciudad","The city","A cidade"),
   ("La playa","The beach","A praia"),
   ("Me quedaría en casa","I'd stay home","Ficaria em casa")),
  ("¿Cual es tu momento favorito del día",
   "What is your favorite time of day?",
   "Qual é sua hora favorita do dia?",
   ("La mañana","Morning","Manhã"),
   ("La tarde","Afternoon","Tarde"),
   ("La noche","Night","Noite"),
   ("La madrugada","Late night","Madrugada")),
  ("¿Qué llevas siempre en tu bolso de viaje?",
   "What do you always carry in your travel bag?",
   "O que você sempre leva na bolsa de viagem?",
   ("Un cargador de teléfono","A phone charger","Um carregador de celular"),
   ("Dinero extra","Extra money","Dinheiro extra"),
   ("Una guía de viaje","A travel guide","Um guia de viagem"),
   ("Un cepillo de dientes","A toothbrush","Uma escova de dentes")),
  ("Qué superpoder te gustaría tener",
   "What superpower would you like to have?",
   "Que superpoder você gostaria de ter?",
   ("Superfuerza","Super strength","Superforca"),
   ("Ser invisible","Invisibility","Ser invisível"),
   ("Detener el tiempo","Stop time","Parar o tempo"),
   ("Volar","Fly","Voar")),
  ("¿Que te gustaría ser?",
   "What would you like to be?",
   "O que você gostaria de ser?",
   ("Un músico famoso","A famous musician","Um músico famoso"),
   ("Un atleta de élite","An elite athlete","Um atleta de elite"),
   ("Un político respetado","A respected politician","Um político respeitado"),
   ("Un gran profesional","A great professional","Um grande profissional")),
  ("Si sólo quedarán dos horas para el fin del mundo ¿Qué harías?",
   "If there were only two hours until the end of the world, what would you do?",
   "Se faltassem duas horas para o fim do mundo, o que você faria?",
   ("Dormir","Sleep","Dormir"),
   ("Buscar una buena vista","Find a good view","Encontrar uma boa vista"),
   ("Cualquier locura que se me ocurra","Any crazy thing I could think of","Qualquer loucura que me ocorra"),
   ("Decirle adiós a mis seres queridos","Say goodbye to my loved ones","Me despedir das pessoas que amo")),
  ("¿Qué preferirías recibir cómo regalo",
   "What would you prefer to receive as a gift?",
   "O que você preferiria ganhar de presente?",
   ("Chocolates","Chocolates","Chocolates"),
   ("Libros","Books","Livros"),
   ("Flores","Flowers","Flores"),
   ("Alcohol","Alcohol","Álcool")),
],
3: [
  ("¿Qué te llevarías a una isla desierta",
   "What would you take to a desert island?",
   "O que você levaria para uma ilha deserta?",
   ("Un libro","A book","Um livro"),
   ("Una radio","A radio","Um rádio"),
   ("Un cuchillo","A knife","Uma faca"),
   ("Un balón","A ball","Uma bola")),
  ("¿Qué prefieres cómo tema de conversación?",
   "What do you prefer as a conversation topic?",
   "O que você prefere como tema de conversa?",
   ("Deportes","Sports","Esportes"),
   ("Música","Music","Música"),
   ("Películas y series","Movies and series","Filmes e séries"),
   ("Política","Politics","Política")),
  ("¿Qué prefieres hacer un fin de semana?",
   "What do you prefer to do on a weekend?",
   "O que você prefere fazer no fim de semana?",
   ("Pescar","Fishing","Pescar"),
   ("Escalar montañas","Mountain climbing","Escalar montanhas"),
   ("Broncearte","Sunbathing","Tomar sol"),
   ("Ir a conciertos","Going to concerts","Ir a shows")),
  ("Una película sobre tu vida ¿Qué tipo de película sería?",
   "A movie about your life – what type would it be?",
   "Um filme sobre sua vida – que tipo seria?",
   ("Una comedia","A comedy","Uma comédia"),
   ("Un drama","A drama","Um drama"),
   ("De Acción","An action movie","De ação"),
   ("Romántica","A romance","Romântico")),
  ("¿Cuál de tus sentidos te gustaría mejorar?",
   "Which of your senses would you like to enhance?",
   "Qual dos seus sentidos você gostaria de melhorar?",
   ("Vista","Sight","Visão"),
   ("Audición","Hearing","Audição"),
   ("Olfato","Smell","Olfato"),
   ("Gusto","Taste","Paladar")),
  ("¿Qué adjetivo te define mejor?",
   "What adjective best defines you?",
   "Qual adjetivo melhor te define?",
   ("Infantil","Childlike","Infantil"),
   ("Alegre","Cheerful","Alegre"),
   ("Sociable","Sociable","Sociável"),
   ("Trabajador","Hardworking","Trabalhador")),
  ("A qué lección preferirías inscribirte?",
   "Which class would you rather sign up for?",
   "Em qual aula você preferiria se inscrever?",
   ("Tiro con arco","Archery","Arco e flecha"),
   ("Cerámica","Ceramics","Cerâmica"),
   ("Esgrima","Fencing","Esgrima"),
   ("Baile","Dance","Dança")),
  ("¿Sin qué no podrías vivir?",
   "What could you not live without?",
   "Sem o que você não poderia viver?",
   ("Música","Music","Música"),
   ("Teléfono móvil","Mobile phone","Celular"),
   ("Mi mascota","My pet","Meu animal de estimação"),
   ("Agua caliente","Hot water","Água quente")),
  ("¿Qué harías si ganaras la loteria",
   "What would you do if you won the lottery?",
   "O que você faria se ganhasse na loteria?",
   ("Comprar un coche nuevo","Buy a new car","Comprar um carro novo"),
   ("Invertir el dinero","Invest the money","Investir o dinheiro"),
   ("Comprar una casa","Buy a house","Comprar uma casa"),
   ("Ayudar a los necesitados","Help those in need","Ajudar os necessitados")),
  ("Qué harías con 2 horas de tiempo libre",
   "What would you do with 2 hours of free time?",
   "O que você faria com 2 horas livres?",
   ("Dormir","Sleep","Dormir"),
   ("Estudiar","Study","Estudar"),
   ("Entrar en mis redes sociales","Browse social media","Acessar redes sociais"),
   ("Jugar videojuegos","Play video games","Jogar videogames")),
  ("¿Qué animal preferirías cómo mascota?",
   "What animal would you prefer as a pet?",
   "Que animal você preferiria como mascote?",
   ("Perro","Dog","Cachorro"),
   ("Gato","Cat","Gato"),
   ("Serpiente","Snake","Cobra"),
   ("Caballo","Horse","Cavalo")),
  ("Cuál es el sueño de tu vida?",
   "What is your life dream?",
   "Qual é o sonho da sua vida?",
   ("Ser millonario","Be a millionaire","Ser milionário"),
   ("Ser famoso","Be famous","Ser famoso"),
   ("Tener muchos hijos","Have many children","Ter muitos filhos"),
   ("Viajar por el mundo","Travel the world","Viajar pelo mundo")),
],
4: [
  ("¿Qué te atrae más?",
   "What attracts you most?",
   "O que mais te atrai?",
   ("Dinero","Money","Dinheiro"),
   ("Familia","Family","Família"),
   ("Estabilidad","Stability","Estabilidade"),
   ("Aventura","Adventure","Aventura")),
  ("¿Qué preferirías ser?",
   "What would you prefer to be?",
   "O que você preferiria ser?",
   ("Más fuerte","Stronger","Mais forte"),
   ("Más alto","Taller","Mais alto"),
   ("Más bajo","Shorter","Mais baixo"),
   ("Más delgado","Slimmer","Mais magro")),
  ("¿Qué papel te gustaría en una obra de teatro?",
   "What role would you like in a play?",
   "Que papel você gostaria em uma peça de teatro?",
   ("El héroe","The hero","O herói"),
   ("El amigo del héroe","The hero's friend","O amigo do herói"),
   ("El villano","The villain","O vilão"),
   ("Un árbol","A tree","Uma árvore")),
  ("A que preferirías poner fin?",
   "What would you rather put an end to?",
   "O que você preferiria acabar?",
   ("La Guerra","War","A Guerra"),
   ("El hambre","Hunger","A Fome"),
   ("Enfermedades","Diseases","Doenças"),
   ("Contaminación","Pollution","Poluição")),
  ("¿Qué actividad prefieres",
   "What activity do you prefer?",
   "Que atividade você prefere?",
   ("Jugar un videojuego","Play a video game","Jogar videogame"),
   ("Ver la televisión","Watch TV","Assistir televisão"),
   ("Hacer ejercicio","Exercise","Fazer exercício"),
   ("Jugar un juego de mesa","Play a board game","Jogar jogo de tabuleiro")),
  ("¿Qué prefieres ver en la televisión?",
   "What do you prefer to watch on TV?",
   "O que você prefere assistir na televisão?",
   ("Deportes","Sports","Esportes"),
   ("Noticias","News","Notícias"),
   ("Documentales","Documentaries","Documentários"),
   ("Reality Shows","Reality Shows","Reality Shows")),
  ("Dondes prefieres pasar tus vacaciones",
   "Where do you prefer to spend your vacation?",
   "Onde você prefere passar suas férias?",
   ("En el caribe","In the Caribbean","No Caribe"),
   ("En las montañas","In the mountains","Nas montanhas"),
   ("En una gran ciudad","In a big city","Em uma grande cidade"),
   ("En un safarí","On a safari","Em um safári")),
  ("Cual es tu medio de transporte favorito",
   "What is your favorite means of transport?",
   "Qual é seu meio de transporte favorito?",
   ("Tren","Train","Trem"),
   ("Barco","Boat","Barco"),
   ("Coche","Car","Carro"),
   ("Avión","Airplane","Avião")),
  ("¿Qué tan inteligente eres?",
   "How intelligent are you?",
   "Quão inteligente você é?",
   ("Brillante","Brilliant","Brilhante"),
   ("Casi un genio","Almost a genius","Quase um gênio"),
   ("Promedio","Average","Mediano"),
   ("Algo Tonto","A bit silly","Um pouco tolo")),
  ("¿Cuál es tu asignatura favorita?",
   "What is your favorite subject?",
   "Qual é sua matéria favorita?",
   ("Matemática","Math","Matemática"),
   ("Ciencia","Science","Ciências"),
   ("Educación Física","Physical Education","Educação Física"),
   ("Arte","Art","Arte")),
  ("Cuando es tu cumpleaños?",
   "When is your birthday?",
   "Quando é seu aniversário?",
   ("Verano","Summer","Verão"),
   ("Otoño","Autumn","Outono"),
   ("Primavera","Spring","Primavera"),
   ("Invierno","Winter","Inverno")),
  ("¿Cuál es tu animal favorito?",
   "What is your favorite animal?",
   "Qual é seu animal favorito?",
   ("Perro","Dog","Cachorro"),
   ("Gato","Cat","Gato"),
   ("Caballo","Horse","Cavalo"),
   ("Conejo","Rabbit","Coelho")),
],
5: [
  ("¿Cuál es tu elemento favorito?",
   "What is your favorite element?",
   "Qual é seu elemento favorito?",
   ("Fuego","Fire","Fogo"),
   ("Aire","Air","Ar"),
   ("Tierra","Earth","Terra"),
   ("Agua","Water","Água")),
  ("¿Cuando eres más productivo?",
   "When are you most productive?",
   "Quando você é mais produtivo?",
   ("Mañana","Morning","Manhã"),
   ("Tarde","Afternoon","Tarde"),
   ("Noche","Night","Noite"),
   ("Madrugada","Late night","Madrugada")),
  ("¿Quién eres en tu grupo de amigos?",
   "Who are you in your friend group?",
   "Quem você é no seu grupo de amigos?",
   ("El lider","The leader","O líder"),
   ("El chistoso","The funny one","O engraçado"),
   ("El creativo","The creative one","O criativo"),
   ("El Leal","The loyal one","O leal")),
  ("¿Cuál es tu fecha favorita?",
   "What is your favorite holiday?",
   "Qual é sua data favorita?",
   ("Navidad","Christmas","Natal"),
   ("Pascuas","Easter","Páscoa"),
   ("San Valentin","Valentine's Day","Dia dos Namorados"),
   ("Halloween","Halloween","Halloween")),
  ("¿Cuál es el trabajo de tus sueños?",
   "What is your dream job?",
   "Qual é o emprego dos seus sonhos?",
   ("Médico","Doctor","Médico"),
   ("Músico","Musician","Músico"),
   ("Atleta","Athlete","Atleta"),
   ("Astronauta","Astronaut","Astronauta")),
  ("¿En qué desearías ser mejor?",
   "What would you like to be better at?",
   "Em que você gostaria de ser melhor?",
   ("Matemáticas","Math","Matemática"),
   ("Canto","Singing","Canto"),
   ("Oratoria","Public speaking","Oratória"),
   ("Deportes","Sports","Esportes")),
  ("¿De qué te gustaría tener un año de suministro?",
   "What would you like a year's supply of?",
   "De que você gostaria de ter um ano de suprimento?",
   ("Cereal","Cereal","Cereal"),
   ("Helado","Ice cream","Sorvete"),
   ("Donas","Donuts","Donuts"),
   ("Chocolate","Chocolate","Chocolate")),
  ("¿Qué actividad preferirías intentar?",
   "Which activity would you rather try?",
   "Qual atividade você preferiria experimentar?",
   ("Ir a un safarí","Go on a safari","Ir em um safári"),
   ("Tirarte en paracaídas","Go skydiving","Saltar de paraquedas"),
   ("Escalar un volcán","Climb a volcano","Escalar um vulcão"),
   ("Nadar con delfines","Swim with dolphins","Nadar com golfinhos")),
  ("¿Cual es tu atividad favorita alrededor de una fogata?",
   "What is your favorite activity around a campfire?",
   "Qual é sua atividade favorita ao redor de uma fogueira?",
   ("Cantar","Singing","Cantar"),
   ("Contar historias de terror","Telling scary stories","Contar histórias de terror"),
   ("Asar malvaviscos","Roasting marshmallows","Assar marshmallows"),
   ("Jugar charadas","Playing charades","Jogar adivinha")),
  ("¿Qué te gusta más de la navidad?",
   "What do you like most about Christmas?",
   "O que você mais gosta no Natal?",
   ("Estar con tu familia","Being with your family","Estar com sua família"),
   ("La fiesta","The party","A festa"),
   ("Comer y beber","Eating and drinking","Comer e beber"),
   ("Los regalos","The gifts","Os presentes")),
  ("¿Que prefieres jugar?",
   "What do you prefer to play?",
   "O que você prefere jogar?",
   ("Videojuegos","Video games","Videogames"),
   ("Juegos de mesa","Board games","Jogos de tabuleiro"),
   ("Cartas","Cards","Cartas"),
   ("Deportes","Sports","Esportes")),
  ("¿Cómo sería tu salida nocturna ideal?",
   "What would your ideal night out be like?",
   "Como seria sua saída noturna ideal?",
   ("Ver un partido de fútbol","Watching a soccer game","Ver um jogo de futebol"),
   ("Ir al teatro","Going to the theater","Ir ao teatro"),
   ("Ir a un concierto","Going to a concert","Ir a um show"),
   ("Ir a un club","Going to a club","Ir a uma boate")),
],
6: [
  ("¿Qué habilidad extraordinria te gustaría tener?",
   "What extraordinary ability would you like to have?",
   "Que habilidade extraordinária você gostaria de ter?",
   ("Volar","Fly","Voar"),
   ("Respirar bajo el agua","Breathe underwater","Respirar embaixo d'água"),
   ("Caminar por las paredes","Walk on walls","Andar pelas paredes"),
   ("Visión de rayos X","X-ray vision","Visão de raio-X")),
  ("¿A quién te gustaría tener de amigo?",
   "Who would you like to have as a friend?",
   "Quem você gostaria de ter como amigo?",
   ("Mi estrella de cine favorita","My favorite movie star","Minha estrela de cinema favorita"),
   ("Mi músico favorito","My favorite musician","Meu músico favorito"),
   ("Mi deportista favorito","My favorite athlete","Meu atleta favorito"),
   ("Mi político favorito","My favorite politician","Meu político favorito")),
  ("¿Qué papel te gustaría en una película?",
   "What role would you like in a movie?",
   "Que papel você gostaria em um filme?",
   ("Un apuesto héroe","A handsome hero","Um herói bonito"),
   ("Un maligno villano","A wicked villain","Um vilão malvado"),
   ("El creativo que se roba la escena","The scene-stealing creative one","O criativo que rouba a cena"),
   ("El mejor amigo del héroe","The hero's best friend","O melhor amigo do herói")),
  ("¿Cómo serían tus vacaciones ideales?",
   "What would your ideal vacation be like?",
   "Como seriam suas férias ideais?",
   ("De relax en la playa","Relaxing at the beach","Relaxando na praia"),
   ("En una gran ciudad con muchos museos","In a big city with many museums","Em uma grande cidade com museus"),
   ("De fiesta en fiesta","Party after party","De festa em festa"),
   ("De senderismo en las montañas","Hiking in the mountains","Fazendo trilhas nas montanhas")),
  ("¿Cuál de estos países te gustaría visitar más?",
   "Which of these countries would you most like to visit?",
   "Qual destes países você mais gostaria de visitar?",
   ("Perú","Peru","Peru"),
   ("Japón","Japan","Japão"),
   ("Francia","France","França"),
   ("EEUU","USA","EUA")),
  ("Cuál es tu red social favorita?",
   "What is your favorite social network?",
   "Qual é sua rede social favorita?",
   ("Instagram","Instagram","Instagram"),
   ("Tik Tok","TikTok","TikTok"),
   ("Twitter","Twitter","Twitter"),
   ("Facebook","Facebook","Facebook")),
  ("¿Qué tipo de bocadillo prefieres?",
   "What type of snack do you prefer?",
   "Que tipo de lanche você prefere?",
   ("Chocolate","Chocolate","Chocolate"),
   ("Patatas fritas","Chips","Batata frita"),
   ("Galletas","Cookies","Biscoitos"),
   ("Fruta","Fruit","Fruta")),
  ("¿Qué harías si fueras invisible?",
   "What would you do if you were invisible?",
   "O que você faria se fosse invisível?",
   ("Hacer bromas","Play pranks","Pregar peças"),
   ("Robar dinero","Steal money","Roubar dinheiro"),
   ("Espiar a la gente","Spy on people","Espionar pessoas"),
   ("Hacer buenas cosas para el mundo","Do good things for the world","Fazer coisas boas pelo mundo")),
  ("Si tuvieras que contratar a alguien ¿A qué cualidad le darías mayor valor?",
   "If you had to hire someone, what quality would you value most?",
   "Se você tivesse que contratar alguém, que qualidade valorizaria mais?",
   ("Apariencia","Appearance","Aparência"),
   ("Experiencia","Experience","Experiência"),
   ("Educación","Education","Educação"),
   ("Carisma","Charisma","Carisma")),
  ("¿Qué situación sería la peor para ti?",
   "What situation would be worst for you?",
   "Qual situação seria a pior para você?",
   ("Apocalipsis Zombie","Zombie apocalypse","Apocalipse Zumbi"),
   ("Rebelión de las máquinas","Robot rebellion","Rebelião das máquinas"),
   ("Invasión extraterrestre","Alien invasion","Invasão alienígena"),
   ("Una gran inundación","A great flood","Uma grande inundação")),
  ("¿Cómo sería tu domingo perfecto?",
   "What would your perfect Sunday be like?",
   "Como seria o seu domingo perfeito?",
   ("Jugar juegos de mesa","Playing board games","Jogar jogos de tabuleiro"),
   ("Un viaje por la carretera","A road trip","Uma viagem de carro"),
   ("Beber en bares","Drinking at bars","Beber em bares"),
   ("Una gran fiesta","A big party","Uma grande festa")),
  ("¿Qué haces para relajarte?",
   "What do you do to relax?",
   "O que você faz para relaxar?",
   ("Tomar sol en el jardín","Sunbathing in the garden","Tomar sol no jardim"),
   ("Tirarme en el sofá","Lounging on the sofa","Deitar no sofá"),
   ("Beber con amigos","Drinking with friends","Beber com amigos"),
   ("Jugar videojuegos","Playing video games","Jogar videogames")),
],
7: [
  ("¿Cuál es tu comida favorita?",
   "What is your favorite food?",
   "Qual é sua comida favorita?",
   ("Sushi","Sushi","Sushi"),
   ("Pasta","Pasta","Macarrão"),
   ("Pizza","Pizza","Pizza"),
   ("Hamburguesas","Burgers","Hambúrgueres")),
  ("¿Que ambiente natural es tu favorito?",
   "What natural setting is your favorite?",
   "Qual ambiente natural é seu favorito?",
   ("El bosque","The forest","A floresta"),
   ("Montañas nevadas","Snowy mountains","Montanhas nevadas"),
   ("La playa","The beach","A praia"),
   ("Un lago y montañas","A lake and mountains","Um lago e montanhas")),
  ("¿Qué te motiva más?",
   "What motivates you most?",
   "O que mais te motiva?",
   ("El éxito","Success","O sucesso"),
   ("La familia","Family","A família"),
   ("El poder","Power","O poder"),
   ("La competencia","Competition","A competição")),
  ("¿Que instrumento te gustaría poder tocar a la perfección?",
   "What instrument would you like to play perfectly?",
   "Que instrumento você gostaria de tocar perfeitamente?",
   ("Guitarra","Guitar","Guitarra"),
   ("Bajo","Bass","Baixo"),
   ("Bateria","Drums","Bateria"),
   ("Piano","Piano","Piano")),
  ("¿Cuál es tu día favorito de la semana?",
   "What is your favorite day of the week?",
   "Qual é seu dia favorito da semana?",
   ("Sábado","Saturday","Sábado"),
   ("Domingo","Sunday","Domingo"),
   ("Viernes","Friday","Sexta-feira"),
   ("Otro","Other","Outro")),
  ("Cuál es tu comida favorita?",
   "What is your favorite meal?",
   "Qual é sua refeição favorita?",
   ("Desayuno","Breakfast","Café da manhã"),
   ("Almuerzo","Lunch","Almoço"),
   ("Merienda","Snack","Lanche"),
   ("Cena","Dinner","Jantar")),
  ("¿Qué género de tv en tu favorito?",
   "What is your favorite TV genre?",
   "Qual é seu gênero favorito de TV?",
   ("Drama","Drama","Drama"),
   ("Comedia","Comedy","Comédia"),
   ("Crimen","Crime","Crime"),
   ("Deporte","Sports","Esporte")),
  ("¿Cuál crees que es tu cualidad más atractiva?",
   "What do you think is your most attractive quality?",
   "Qual você acha que é sua qualidade mais atraente?",
   ("Apariencia","Appearance","Aparência"),
   ("Inteligencia","Intelligence","Inteligência"),
   ("Ambición","Ambition","Ambição"),
   ("Humor","Humor","Humor")),
  ("¿Qué deberías mejorar?",
   "What should you improve?",
   "O que você deveria melhorar?",
   ("Tu dieta","Your diet","Sua dieta"),
   ("Carrera profesional","Your career","Carreira profissional"),
   ("Finanzas","Finances","Finanças"),
   ("Cultura","Culture","Cultura")),
  ("¿Qué superhéroe te gustaría ser?",
   "What superhero would you like to be?",
   "Que super-herói você gostaria de ser?",
   ("Batman","Batman","Batman"),
   ("Superman","Superman","Superman"),
   ("Spiderman","Spiderman","Homem-Aranha"),
   ("La mujer maravilla","Wonder Woman","Mulher Maravilha")),
  ("¿Cómo sería tu primera cita perfecta?",
   "What would your perfect first date be like?",
   "Como seria seu primeiro encontro perfeito?",
   ("Cenar en casa","Dinner at home","Jantar em casa"),
   ("Bailar y beber en un club","Dancing and drinking at a club","Dançar e beber em uma boate"),
   ("Ir a un concierto","Going to a concert","Ir a um show"),
   ("Ir al cine","Going to the movies","Ir ao cinema")),
  ("¿Qué tan seguido haces ejercicio?",
   "How often do you exercise?",
   "Com que frequência você se exercita?",
   ("Todos los días","Every day","Todos os dias"),
   ("5 veces a la semana","5 times a week","5 vezes por semana"),
   ("2 o 3 veces por semana","2 or 3 times a week","2 ou 3 vezes por semana"),
   ("Una vez o nunca","Once or never","Uma vez ou nunca")),
],
8: [
  ("¿Cómo prefieres pasar una hora de tiempo libre?",
   "How do you prefer to spend an hour of free time?",
   "Como você prefere passar uma hora de tempo livre?",
   ("Yendo de compras","Shopping","Indo às compras"),
   ("Durmiendo","Sleeping","Dormindo"),
   ("En el gimnasio","At the gym","Na academia"),
   ("Viendo TV","Watching TV","Assistindo TV")),
  ("¿A quién elegirías para cambiar de vida por un año?",
   "Whose life would you choose to swap for a year?",
   "Com quem você trocaria de vida por um ano?",
   ("Tu jefe","Your boss","Seu chefe"),
   ("Tu hermano o hermana","Your brother or sister","Seu irmão ou irmã"),
   ("Un amigo","A friend","Um amigo"),
   ("Tu pareja","Your partner","Seu parceiro")),
  ("Por lo general ¿Qué sueles usar más a menudo?",
   "In general, what do you use most often?",
   "Em geral, o que você usa com mais frequência?",
   ("El corazón","Your heart","O coração"),
   ("La lógica","Logic","A lógica"),
   ("El dinero","Money","O dinheiro"),
   ("La experiencia","Experience","A experiência")),
  ("¿Que te daría mayor felicidad?",
   "What would give you the most happiness?",
   "O que te daria mais felicidade?",
   ("Viajar por el mundo","Traveling the world","Viajar pelo mundo"),
   ("Hacer más amigos","Making more friends","Fazer mais amigos"),
   ("Tener más dinero","Having more money","Ter mais dinheiro"),
   ("Estar en mejor forma","Being in better shape","Estar em melhor forma")),
  ("¿Cuál es tu mayor prioridad ahora mismo?",
   "What is your biggest priority right now?",
   "Qual é sua maior prioridade agora?",
   ("Relación sentimental","Romantic relationship","Relacionamento"),
   ("Carrera profesional","Career","Carreira"),
   ("Reputación","Reputation","Reputação"),
   ("Éxito","Success","Sucesso")),
  ("Cuál es tu miedo más grande?",
   "What is your greatest fear?",
   "Qual é seu maior medo?",
   ("La muerte","Death","A morte"),
   ("Estar solo","Being alone","Ficar sozinho"),
   ("Los bichos","Bugs","Os insetos"),
   ("Espacios pequeños","Small spaces","Espaços pequenos")),
  ("¿Cómo calificarías tu forma de bailar?",
   "How would you rate your dancing?",
   "Como você avaliaria sua dança?",
   ("Desastrosa","Disastrous","Desastrosa"),
   ("Mala","Bad","Ruim"),
   ("Promedio","Average","Mediana"),
   ("Genial","Great","Ótima")),
  ("¿Qué te gustaría más?",
   "What would you prefer?",
   "O que você preferiria?",
   ("Ser más alto","Be taller","Ser mais alto"),
   ("Ser más delgado","Be slimmer","Ser mais magro"),
   ("Ser más jóven","Be younger","Ser mais jovem"),
   ("Ser más bajo","Be shorter","Ser mais baixo")),
  ("¿Qué preferirías hacer?",
   "What would you rather do?",
   "O que você preferiria fazer?",
   ("Manejar un moto de agua","Ride a jet ski","Andar de jet ski"),
   ("Bucear","Scuba dive","Mergulhar"),
   ("Saltar en paracaídas","Go skydiving","Saltar de paraquedas"),
   ("Pilotear un avión","Fly a plane","Pilotar um avião")),
  ("¿Cómo calificarías tu forma de cantar?",
   "How would you rate your singing?",
   "Como você avaliaria seu canto?",
   ("Excelente","Excellent","Excelente"),
   ("Promedio","Average","Mediano"),
   ("Mala","Bad","Ruim"),
   ("Desastrosa","Disastrous","Desastrosa")),
  ("¿Qué priorizas en tus vacaciones?",
   "What do you prioritize on vacation?",
   "O que você prioriza nas férias?",
   ("La comida","Food","A comida"),
   ("El alojamiento","Accommodation","A acomodação"),
   ("Espectáculos","Shows","Espetáculos"),
   ("La compania","Company","A companhia")),
  ("¿En qué eres peor?",
   "What are you worst at?",
   "Em que você é pior?",
   ("Bailando","Dancing","Dançar"),
   ("Cantando","Singing","Cantar"),
   ("Dibujando","Drawing","Desenhar"),
   ("Deportes","Sports","Esportes")),
],
9: [
  ("¿Qué preferirías tener en tu casa?",
   "What would you prefer to have in your house?",
   "O que você preferiria ter em sua casa?",
   ("Una sala de juegos","A game room","Uma sala de jogos"),
   ("Un gimnasio","A gym","Uma academia"),
   ("Un estudio","A studio","Um estúdio"),
   ("Una piscina","A pool","Uma piscina")),
  ("¿Cómo calificarías tu puntualidad?",
   "How would you rate your punctuality?",
   "Como você avaliaria sua pontualidade?",
   ("Excelente","Excellent","Excelente"),
   ("Buena","Good","Boa"),
   ("Promedio","Average","Mediana"),
   ("Muy mala","Very bad","Muito ruim")),
  ("¿Cómo serían unas vaciones de pesadilla?",
   "What would a nightmare vacation look like?",
   "Como seriam umas férias de pesadelo?",
   ("Caminando mucho","Walking a lot","Caminhando muito"),
   ("En un campamento","At a camp","Em um acampamento"),
   ("En la playa","At the beach","Na praia"),
   ("En una ciudad","In a city","Em uma cidade")),
  ("¿Cuál es tu género literario favorito?",
   "What is your favorite literary genre?",
   "Qual é seu gênero literário favorito?",
   ("Romance","Romance","Romance"),
   ("Crimen","Crime","Crime"),
   ("Historia","History","História"),
   ("Biográficos","Biographies","Biografias")),
  ("¿Qué empleo se ajusta mejor a tu perfil?",
   "What job best fits your profile?",
   "Que emprego melhor se encaixa no seu perfil?",
   ("Doctor","Doctor","Médico"),
   ("Maestro","Teacher","Professor"),
   ("Abogado","Lawyer","Advogado"),
   ("Vendedor","Salesperson","Vendedor")),
  ("¿Cómo eres en la cocina?",
   "How are you in the kitchen?",
   "Como você é na cozinha?",
   ("Todo un chef","A real chef","Um chef de verdade"),
   ("Nada mal","Not bad","Nada mal"),
   ("Todo se quema","Everything burns","Tudo queima"),
   ("No cocinas","You don't cook","Não cozinha")),
  ("Elige una de las siguientes mascotas",
   "Choose one of the following pets",
   "Escolha um dos seguintes animais de estimação",
   ("Una cobra","A cobra","Uma cobra"),
   ("Un chimpancé","A chimpanzee","Um chimpanzé"),
   ("Un hámster","A hamster","Um hamster"),
   ("Un elefante","An elephant","Um elefante")),
  ("¿Qué monumento te gustaría visitar?",
   "What monument would you like to visit?",
   "Que monumento você gostaria de visitar?",
   ("La estatua de la libertad","The Statue of Liberty","A Estátua da Liberdade"),
   ("La gran muralla china","The Great Wall of China","A Grande Muralha da China"),
   ("La torre Eiffel","The Eiffel Tower","A Torre Eiffel"),
   ("Las pirámides de Egipto","The Egyptian Pyramids","As Pirâmides do Egito")),
  ("¿Qué utilizas más a menudo?",
   "What do you use most often?",
   "O que você usa com mais frequência?",
   ("Netflix","Netflix","Netflix"),
   ("Amazon Prime","Amazon Prime","Amazon Prime"),
   ("Disney+","Disney+","Disney+"),
   ("Youtube","YouTube","YouTube")),
  ("¿Qué tipo de clima prefieres?",
   "What type of weather do you prefer?",
   "Que tipo de clima você prefere?",
   ("Soleado","Sunny","Ensolarado"),
   ("Lluvioso","Rainy","Chuvoso"),
   ("Nevado","Snowy","Nevado"),
   ("Ventoso","Windy","Ventoso")),
  ("¿Qué prefieres para tarjeta de regalo?",
   "What do you prefer for a gift card?",
   "O que você prefere em um cartão presente?",
   ("Comida","Food","Comida"),
   ("Viajes","Travel","Viagens"),
   ("Cosméticos","Cosmetics","Cosméticos"),
   ("Videojuegos","Video games","Videogames")),
  ("¿Cuál piensas que es tu mayor fortaleza?",
   "What do you think is your greatest strength?",
   "Qual você acha que é sua maior força?",
   ("Buen humor","Good humor","Bom humor"),
   ("Lealtad","Loyalty","Lealdade"),
   ("Ambición","Ambition","Ambição"),
   ("Calidez","Warmth","Calidez")),
],
10: [
  ("Tienes que renunciar a una cosa por todo un mes ¿Cuál sería?",
   "You have to give up one thing for a whole month. Which would it be?",
   "Você tem que abrir mão de uma coisa por um mês inteiro. Qual seria?",
   ("Teléfono móvil","Mobile phone","Celular"),
   ("Redes sociales","Social media","Redes sociais"),
   ("Videojuegos","Video games","Videogames"),
   ("Chocolate","Chocolate","Chocolate")),
  ("¿Cuál es tu mayor preocupación?",
   "What is your biggest concern?",
   "Qual é sua maior preocupação?",
   ("Salud","Health","Saúde"),
   ("Trabajo","Work","Trabalho"),
   ("Dinero","Money","Dinheiro"),
   ("Familia","Family","Família")),
  ("¿En donde disfrutas más?",
   "Where do you enjoy yourself most?",
   "Onde você se diverte mais?",
   ("En una boda","At a wedding","Em um casamento"),
   ("En un cumpleaños","At a birthday","Em um aniversário"),
   ("En Navidad","At Christmas","No Natal"),
   ("En Año Nuevo","At New Year's","No Ano Novo")),
  ("¿Cuántos libros lees al mes?",
   "How many books do you read per month?",
   "Quantos livros você lê por mês?",
   ("0","0","0"),
   ("1","1","1"),
   ("2","2","2"),
   ("Más de tres","More than three","Mais de três")),
  ("Si te hicieran una fiesta ¿Qué sentirías?",
   "If someone threw you a party, how would you feel?",
   "Se alguém fizesse uma festa para você, como se sentiria?",
   ("Emoción","Excitement","Emoção"),
   ("Agradecimiento","Gratitude","Gratidão"),
   ("Verguenza","Embarrassment","Vergonha"),
   ("Euforia","Euphoria","Euforia")),
  ("¿Qué preferirías tener en tu casa?",
   "What would you prefer to have at home?",
   "O que você preferiria ter em casa?",
   ("Un trampolín","A trampoline","Uma cama elástica"),
   ("Una piscina olímpica","An Olympic pool","Uma piscina olímpica"),
   ("Una casita del árbol","A treehouse","Uma casa na árvore"),
   ("Una cancja de tennis","A tennis court","Uma quadra de tênis")),
  ("¿Quién es la primera persona a la que cuentas una buena noticia?",
   "Who is the first person you tell good news to?",
   "Quem é a primeira pessoa para quem você conta uma boa notícia?",
   ("Tus padres","Your parents","Seus pais"),
   ("Tu mejor amigo","Your best friend","Seu melhor amigo"),
   ("Tu pareja","Your partner","Seu parceiro"),
   ("Tu hermano","Your sibling","Seu irmão")),
  ("¿Qué extravías más a menudo?",
   "What do you lose most often?",
   "O que você perde com mais frequência?",
   ("Teléfono móvil","Mobile phone","Celular"),
   ("Cartera","Wallet","Carteira"),
   ("Anteojos","Glasses","Óculos"),
   ("Llaves","Keys","Chaves")),
  ("¿Qué te parece más divertido?",
   "What do you find most fun?",
   "O que você acha mais divertido?",
   ("Una caminata tranquila","A leisurely walk","Uma caminhada tranquila"),
   ("Salir a bailar","Going dancing","Sair para dançar"),
   ("Tomar un café con un amigo","Having coffee with a friend","Tomar café com um amigo"),
   ("Hacer deportes","Playing sports","Praticar esportes")),
  ("¿Qúe factor es más importante a la hora de comprar algo?",
   "What factor is most important when buying something?",
   "Que fator é mais importante na hora de comprar algo?",
   ("La calidad","Quality","A qualidade"),
   ("El precio","Price","O preço"),
   ("La moda","Fashion","A moda"),
   ("Lo práctico","Practicality","O prático")),
  ("¿Cuál de las siguientes cosas ansías más?",
   "Which of the following do you crave most?",
   "Qual das seguintes coisas você mais anseia?",
   ("Conocimientos","Knowledge","Conhecimento"),
   ("Dinero","Money","Dinheiro"),
   ("Comida","Food","Comida"),
   ("Tiempo de relax","Relaxation time","Tempo de descanso")),
  ("Si tuvieras que dedicar tiempo a una sola de estas cosas por el resto de tu vida ¿Cuál eliges?",
   "If you had to dedicate time to only one of these things for the rest of your life, which would you choose?",
   "Se tivesse que dedicar tempo a apenas uma dessas coisas pelo resto da vida, qual escolheria?",
   ("Familia","Family","Família"),
   ("Amigos","Friends","Amigos"),
   ("Trabajo","Work","Trabalho"),
   ("Pasatiempos","Hobbies","Hobbies")),
],
# ─── Adult packs ─────────────────────────────────────────────────────────────
11: [
  ("¿Con cuántas personas tuviste sexo?",
   "How many people have you had sex with?",
   "Com quantas pessoas você já fez sexo?",
   ("1-3","1-3","1-3"),
   ("3-10","3-10","3-10"),
   ("10-20","10-20","10-20"),
   ("20+","20+","20+")),
  ("¿Jugaste Strip Poker alguna vez?",
   "Have you ever played Strip Poker?",
   "Você já jogou Strip Poker?",
   ("Sí y lo volvería a hacer","Yes and I'd do it again","Sim e faria de novo"),
   ("No pero quiero hacerlo","No but I want to","Não mas quero"),
   ("Si pero no quiero que se repita","Yes but I don't want to again","Sim mas não quero repetir"),
   ("No lo haría jamás","I'd never do it","Jamais faria")),
  ("¿Cual es el lugar más incómodo donde lo has hecho?",
   "What is the most uncomfortable place you've had sex?",
   "Qual é o lugar mais desconfortável onde você já fez sexo?",
   ("En un baño","In a bathroom","No banheiro"),
   ("En la playa","On the beach","Na praia"),
   ("En un auto","In a car","Em um carro"),
   ("En la calle","On the street","Na rua")),
  ("Si te proponen grabar un video xxx, tú:",
   "If someone proposes making an adult video, you:",
   "Se te propuserem gravar um vídeo adulto, você:",
   ("Te enojas","Get angry","Fica com raiva"),
   ("Te excitas","Get excited","Fica excitado/a"),
   ("Te ríes","Laugh","Ri"),
   ("Te averguenzas","Get embarrassed","Fica envergonhado/a")),
  ("Si sólo pudieras tocarme en una parte del cuerpo ¿Cuál sería?",
   "If you could only touch me on one body part, which would it be?",
   "Se pudesse me tocar em apenas uma parte do corpo, qual seria?",
   ("La cara","The face","O rosto"),
   ("El pecho","The chest","O peito"),
   ("Las piernas","The legs","As pernas"),
   ("Partes íntimas","Intimate parts","Partes íntimas")),
  ("¿Cuánto tiempo has estado sin acostarte con nadie?",
   "How long have you gone without having sex?",
   "Quanto tempo você ficou sem fazer sexo?",
   ("Una semana","One week","Uma semana"),
   ("Un mes","One month","Um mês"),
   ("Seis meses","Six months","Seis meses"),
   ("Más de un año","More than a year","Mais de um ano")),
  ("¿Harías un trío?",
   "Would you have a threesome?",
   "Você faria um trio?",
   ("Sí, con otra chica","Yes, with another girl","Sim, com outra garota"),
   ("Sí, con otro chico","Yes, with another guy","Sim, com outro rapaz"),
   ("No ahora, quizás más adelante","Not now, maybe later","Não agora, talvez mais tarde"),
   ("Jamás","Never","Jamais")),
  ("¿Qué es lo que más te excita?",
   "What turns you on the most?",
   "O que te excita mais?",
   ("Un buen cuerpo","A good body","Um bom corpo"),
   ("La inteligencia","Intelligence","A inteligência"),
   ("El atrevimiento","Boldness","A ousadia"),
   ("La bondad","Kindness","A bondade")),
  ("¿Qué te parece más divertido?",
   "What do you find most fun?",
   "O que você acha mais divertido?",
   ("Una caminata tranquila","A leisurely walk","Uma caminhada tranquila"),
   ("Salir a bailar","Going dancing","Sair para dançar"),
   ("Tomar un café con un amigo","Having coffee with a friend","Tomar café com um amigo"),
   ("Hacer deportes","Playing sports","Praticar esportes")),
  ("¿A qué todavía no te animas?",
   "What are you not yet daring enough to try?",
   "O que você ainda não tem coragem de fazer?",
   ("Sadomasoquismo","Sadomasochism","Sadomasoquismo"),
   ("Sexo anal","Anal sex","Sexo anal"),
   ("Un trío","A threesome","Um trio"),
   ("Disfraces","Costumes","Fantasias")),
  ("¿En que lugar público te gustaría hacerlo?",
   "In what public place would you like to do it?",
   "Em que lugar público você gostaria de fazer?",
   ("Calle","Street","Rua"),
   ("Una plaza","A square","Uma praça"),
   ("La playa","The beach","A praia"),
   ("Un bosque","A forest","Uma floresta")),
  ("¿Alguna vez tuviste un sueño erótico con alguna persona que no debías?",
   "Have you ever had an erotic dream about someone you shouldn't have?",
   "Você já teve um sonho erótico com alguém que não deveria?",
   ("Un amigo/a","A friend","Um/a amigo/a"),
   ("Un/a familiar","A family member","Um/a familiar"),
   ("Un/a compañero/a","A coworker","Um/a colega"),
   ("Nunca","Never","Nunca")),
],
12: [
  ("¿Cuál fue el máximo de personas con las que has tenido sexo al mismo tiempo?",
   "What is the most people you've had sex with at the same time?",
   "Qual foi o máximo de pessoas com quem você fez sexo ao mesmo tempo?",
   ("Nunca con más de una","Never more than one","Nunca com mais de uma"),
   ("Dos","Two","Duas"),
   ("Tres","Three","Três"),
   ("Más de tres","More than three","Mais de três")),
  ("¿Cuánto tiempo puedes estar haciendólo sin parar?",
   "How long can you go without stopping?",
   "Quanto tempo você consegue aguentar sem parar?",
   ("Cinco minutos","Five minutes","Cinco minutos"),
   ("Treinta minutos","Thirty minutes","Trinta minutos"),
   ("Una hora","One hour","Uma hora"),
   ("Más de dos horas","More than two hours","Mais de duas horas")),
  ("¿Alguna vez estuviste en un club swingers?",
   "Have you ever been to a swingers club?",
   "Você já esteve em um clube de swing?",
   ("Sí y volvería a hacerlo","Yes and I'd do it again","Sim e faria de novo"),
   ("Sí pero no me gustó","Yes but I didn't like it","Sim mas não gostei"),
   ("No pero me da curiosidad","No but I'm curious","Não mas tenho curiosidade"),
   ("Jamás lo haría","I'd never do it","Jamais faria")),
  ("¿Qué personaje ficticio te consideras debajo de las sábanas?",
   "What fictional character are you in bed?",
   "Que personagem fictício você é debaixo das lençóis?",
   ("Ironman","Iron Man","Homem de Ferro"),
   ("La mujer maravilla","Wonder Woman","Mulher Maravilha"),
   ("La bella durmiente","Sleeping Beauty","A Bela Adormecida"),
   ("Drácula","Dracula","Drácula")),
  ("¿Cómo te gusta que te hagan sexo oral?",
   "How do you like oral sex?",
   "Como você gosta de sexo oral?",
   ("Con cariño","With tenderness","Com carinho"),
   ("Bien guarro","Real dirty","Bem safado"),
   ("Extremo","Extreme","Extremo"),
   ("No me gusta","I don't like it","Não gosto")),
  ("¿Qué es lo más lejos a lo que has llegado en una primera cita?",
   "What's the furthest you've gone on a first date?",
   "Até onde você foi em um primeiro encontro?",
   ("Un beso francés","A French kiss","Um beijo de língua"),
   ("Sexo oral","Oral sex","Sexo oral"),
   ("Sexo tradicional","Traditional sex","Sexo tradicional"),
   ("Sexo con otras personas","Sex with other people","Sexo com outras pessoas")),
  ("¿Cual es tu especialidad?",
   "What is your specialty?",
   "Qual é sua especialidade?",
   ("Los disfraces","Costumes","As fantasias"),
   ("Los juguetes","Toys","Os brinquedos"),
   ("La previa y el sexo oral","Foreplay and oral sex","A previa e o sexo oral"),
   ("Tu forma de moverte en la cama","The way you move in bed","A forma como você se move na cama")),
  ("Si se vienen en tu boca, tú:",
   "If they come in your mouth, you:",
   "Se gozarem na sua boca, você:",
   ("Escupes","Spit","Cospe"),
   ("Tragas","Swallow","Engole"),
   ("Pides más","Ask for more","Pede mais"),
   ("Te enojas","Get angry","Fica com raiva")),
  ("¿De qué parte de tu cuerpo estás más orgulloso/a?",
   "What body part are you most proud of?",
   "Qual parte do seu corpo você tem mais orgulho?",
   ("Tu carita","Your face","Seu rosto"),
   ("Tu colita","Your butt","Sua bunda"),
   ("Tu pecho","Your chest","Seu peito"),
   ("Tu cosita","Your private parts","Sua parte íntima")),
  ("¿Qué es lo más embarazoso que te ha pasado estando con alguien?",
   "What's the most embarrassing thing that's happened to you during sex?",
   "Qual foi a coisa mais embaraçosa que aconteceu com você durante o sexo?",
   ("No funcionó el amigo","It didn't work","Não funcionou"),
   ("Alguien se vino demasiado rápido","Someone came too fast","Alguém veio rápido demais"),
   ("Nos encontraron","We got caught","Nos encontraram"),
   ("Hubiera sido mejor tener un inodoro cerca","Should've had a toilet nearby","Seria melhor ter um banheiro por perto")),
  ("¿Alguna fantasia que no hayas cumplido?",
   "Any fantasy you haven't fulfilled yet?",
   "Alguma fantasia que você ainda não realizou?",
   ("En un avión","On a plane","Em um avião"),
   ("En un lugar público","In a public place","Em um lugar público"),
   ("En un auto en movimiento","In a moving car","Em um carro em movimento"),
   ("Juego de roles con disfraces","Role play with costumes","Jogo de papéis com fantasias")),
  ("¿Con qué frecuencia te gusta tener sexo?",
   "How often do you like to have sex?",
   "Com que frequência você gosta de fazer sexo?",
   ("Todos los días","Every day","Todos os dias"),
   ("Día por medio","Every other day","Dia sim, dia não"),
   ("Una vez por semana","Once a week","Uma vez por semana"),
   ("Una vez al mes","Once a month","Uma vez por mês")),
],
13: [
  ("¿Qué posición te gusta más?",
   "What position do you like most?",
   "Que posição você mais gosta?",
   ("Misionero","Missionary","Missionário"),
   ("De perrito","Doggy style","De quatro"),
   ("A cococho","Cowgirl","Cowgirl"),
   ("Boca abajo","Face down","De bruços")),
  ("¿Cual es tu manera de seducir?",
   "What is your way of seducing?",
   "Qual é sua maneira de seduzir?",
   ("Halagando a la otra persona","Complimenting the other person","Elogiando a outra pessoa"),
   ("Hablando de tus proezas","Talking about your feats","Falando de suas façanhas"),
   ("Haciendo reir a la otra persona","Making the other person laugh","Fazendo a outra pessoa rir"),
   ("Con una mirada penetrante","With a piercing look","Com um olhar penetrante")),
  ("¿Te has acostado con una ex pareja después de cortar?",
   "Have you slept with an ex after breaking up?",
   "Você já dormiu com um ex após o término?",
   ("Sí, al poco tiempo","Yes, shortly after","Sim, pouco tempo depois"),
   ("Sí, un reencuentro por los viejos tiempos","Yes, a reunion for old times' sake","Sim, um reencontro pela saudade"),
   ("No pero nos hemos contactado","No but we've been in touch","Não mas nos falamos"),
   ("Jamás lo haría","I'd never do it","Jamais faria")),
  ("¿Que clase de juguetes te gusta?",
   "What kind of toys do you like?",
   "Que tipo de brinquedos você gosta?",
   ("Animalitos","Small animals","Animaizinhos"),
   ("Collares","Collars","Coleiras"),
   ("Cosas que me hagan doler y vibrar","Things that make me hurt and vibrate","Coisas que me façam doer e vibrar"),
   ("Ninguna","None","Nenhum")),
  ("¿Qué clase de disfraz es tu favorito?",
   "What kind of costume is your favorite?",
   "Que tipo de fantasia é a sua favorita?",
   ("Policia","Police","Policial"),
   ("Anime","Anime","Anime"),
   ("Colegiala","Schoolgirl","Colegial"),
   ("Superhéroes","Superheroes","Super-heróis")),
  ("¿Cómo te gustaría que se vistiera tu pareja para dormir contigo?",
   "How would you like your partner to dress to sleep with you?",
   "Como você gostaria que seu parceiro se vestisse para dormir com você?",
   ("Encaje","Lace","Renda"),
   ("Camiseta larga","Long t-shirt","Camiseta longa"),
   ("Desnuda","Naked","Nua/o"),
   ("Pijama","Pajamas","Pijama")),
  ("¿Te gustaría que te aten?",
   "Would you like to be tied up?",
   "Você gostaria de ser amarrado/a?",
   ("Con una soga","With a rope","Com uma corda"),
   ("Con esposas","With handcuffs","Com algemas"),
   ("Con sogas y vendas en los ojos","With ropes and a blindfold","Com cordas e venda nos olhos"),
   ("No me gustaría","I wouldn't like it","Não gostaria")),
  ("Si se vienen en tu boca, tú:",
   "If they come in your mouth, you:",
   "Se gozarem na sua boca, você:",
   ("Escupes","Spit","Cospe"),
   ("Tragas","Swallow","Engole"),
   ("Pides más","Ask for more","Pede mais"),
   ("Te enojas","Get angry","Fica com raiva")),
  ("¿Qué es lo más atrevido que has hecho en un cine?",
   "What is the boldest thing you've done in a movie theater?",
   "Qual é a coisa mais ousada que você fez no cinema?",
   ("Un beso","A kiss","Um beijo"),
   ("Dedos mojados","Fingering","Dedos molhados"),
   ("Sexo oral","Oral sex","Sexo oral"),
   ("Sexo en lo alto de la sala","Sex at the back of the theater","Sexo no fundo da sala")),
  ("¿A qué edad perdiste la virginidad?",
   "At what age did you lose your virginity?",
   "Com que idade você perdeu a virgindade?",
   ("13-15","13-15","13-15"),
   ("16-18","16-18","16-18"),
   ("18-22","18-22","18-22"),
   ("22+","22+","22+")),
  ("¿Que es lo más sucio que has pensado hacer con tu pareja?",
   "What is the dirtiest thing you've thought of doing with your partner?",
   "Qual é a coisa mais suja que você já pensou em fazer com seu parceiro?",
   ("Sexo anal","Anal sex","Sexo anal"),
   ("Un trío","A threesome","Um trio"),
   ("Intercambio de parejas","Swinging","Troca de casais"),
   ("Una orgía","An orgy","Uma orgia")),
  ("¿Alguna vez te has masturbado en un baño público?",
   "Have you ever masturbated in a public bathroom?",
   "Você já se masturbou em um banheiro público?",
   ("En el trabajo","At work","No trabalho"),
   ("En la escuela","At school","Na escola"),
   ("En una estación de servicio","At a gas station","Em um posto de gasolina"),
   ("Nunca","Never","Nunca")),
],
14: [
  ("¿Con qué frecuencia te masturbas?",
   "How often do you masturbate?",
   "Com que frequência você se masturba?",
   ("Todos los días","Every day","Todos os dias"),
   ("Cada dos o tres días","Every two or three days","A cada dois ou três dias"),
   ("Una vez por semana","Once a week","Uma vez por semana"),
   ("Una vez al mes","Once a month","Uma vez por mês")),
  ("¿Qué actitud te gusta que tenga tu pareja en la cama?",
   "What attitude do you like your partner to have in bed?",
   "Que atitude você gosta que seu parceiro tenha na cama?",
   ("Dominante","Dominant","Dominante"),
   ("Pasiva","Passive","Passiva"),
   ("Sumisa","Submissive","Submissa"),
   ("Violenta","Rough","Violenta")),
  ("¿Cuál es el máximo de orgasmos que has tenido en la misma noche?",
   "What is the most orgasms you've had in one night?",
   "Qual é o máximo de orgasmos que você já teve em uma noite?",
   ("Apenas uno","Just one","Apenas um"),
   ("Entre dos y tres","Between two and three","Entre dois e três"),
   ("Entre cuatro y seis","Between four and six","Entre quatro e seis"),
   ("Más de siete","More than seven","Mais de sete")),
  ("¿En cuánto llegas al orgasmo en promedio?",
   "How long does it take you to orgasm on average?",
   "Em quanto tempo você chega ao orgasmo em média?",
   ("Cuestión de segundos","A matter of seconds","Questão de segundos"),
   ("Cinco minutos","Five minutes","Cinco minutos"),
   ("Veinte minutos","Twenty minutes","Vinte minutos"),
   ("Una hora","One hour","Uma hora")),
  ("¿Donde te gustaría recibir un masaje?",
   "Where would you like to receive a massage?",
   "Onde você gostaria de receber uma massagem?",
   ("Cuello","Neck","Pescoço"),
   ("Espalda","Back","Costas"),
   ("Cola","Butt","Bunda"),
   ("Pies","Feet","Pés")),
  ("¿Qué opinas de los chupones?",
   "What do you think of hickeys?",
   "O que você acha de chupões?",
   ("Es infantil","It's childish","É infantil"),
   ("Marco mi territorio","I'm marking my territory","Marco meu território"),
   ("Me dan verguenza","They embarrass me","Tenho vergonha"),
   ("Los llevo con orgullo","I wear them with pride","Uso com orgulho")),
  ("¿Que es lo más salvaje que has hecho?",
   "What is the wildest thing you've done?",
   "Qual é a coisa mais selvagem que você já fez?",
   ("Romper un condón","Break a condom","Romper uma camisinha"),
   ("Romper una cama","Break a bed","Quebrar uma cama"),
   ("Sangrar por hacerlo tan fuerte","Bleed from doing it too hard","Sangrar de tanto fazer"),
   ("Dar una nalgada muy dolorosa","Give a very painful spanking","Dar uma palmada muito dolorosa")),
  ("¿Cuál es tu fetiche?",
   "What is your fetish?",
   "Qual é o seu fetiche?",
   ("Sexo con los pies","Foot fetish","Fetiche com pés"),
   ("Pegarle a tu pareja","Hitting your partner","Bater no parceiro"),
   ("Escupir durante el sexo oral","Spitting during oral sex","Cuspir durante o sexo oral"),
   ("Otro bastante raro","Something quite unusual","Outro bem esquisito")),
  ("¿Qué pasa cuando hay conocidos en el cuarto de al lado?",
   "What happens when there are people you know in the next room?",
   "O que acontece quando há conhecidos no quarto ao lado?",
   ("Se folla más fuerte","It's even wilder","Faz mais forte"),
   ("Se grita sin pudor","Screaming shamelessly","Grita sem pudor"),
   ("Se trata de guardar el mayor silencio posible","Try to be as quiet as possible","Tenta ficar bem quieto"),
   ("No se hace nada por respeto","Nothing happens out of respect","Não faz nada por respeito")),
  ("¿Qué parte del cuerpo de tu pareja te gusta chupar?",
   "What body part of your partner do you like to suck?",
   "Qual parte do corpo do seu parceiro você gosta de chupar?",
   ("El cuello","The neck","O pescoço"),
   ("Los pies","The feet","Os pés"),
   ("Los pechos","The breasts","Os peitos"),
   ("Sus partes íntimas","Their intimate parts","Suas partes íntimas")),
  ("¿Cómo crees que la pasarías en una orgía?",
   "How do you think you'd do at an orgy?",
   "Como você acha que se sairia em uma orgia?",
   ("¡Genial!","Great!","Ótimo!"),
   ("Me daría verguenza","I'd be embarrassed","Ficaria com vergonha"),
   ("Depende de cómo la pase mi pareja","Depends on how my partner does","Depende de como meu parceiro se saísse"),
   ("Nunca iría a una orgía y menos con mi amor","I'd never go to an orgy, especially not with my love","Jamais iria a uma orgia, muito menos com meu amor")),
  ("¿Tuviste relaciones de una noche?",
   "Have you had one-night stands?",
   "Você já teve ficadas de uma noite?",
   ("Una vez","Once","Uma vez"),
   ("Más de tres veces","More than three times","Mais de três vezes"),
   ("Más de diez veces","More than ten times","Mais de dez vezes"),
   ("Nunca","Never","Nunca")),
],
15: [
  ("¿En donde te gusta más tener sexo?",
   "Where do you like having sex the most?",
   "Onde você mais gosta de fazer sexo?",
   ("En la cama","In bed","Na cama"),
   ("En el sillón","On the couch","No sofá"),
   ("En el baño","In the bathroom","No banheiro"),
   ("Sobre la mesa o el lavarropas","On the table or washing machine","Na mesa ou na máquina de lavar")),
  ("¿Venderías nudes?¿A qué precio?",
   "Would you sell nudes? At what price?",
   "Você venderia nudes? A que preço?",
   ("Mil dólares","$1,000","Mil dólares"),
   ("Diez mil dólares","$10,000","Dez mil dólares"),
   ("Cien mil dólares o más","$100,000 or more","Cem mil dólares ou mais"),
   ("No vendería","I wouldn't sell","Não venderia")),
  ("¿Por qué precio dejarías que un desconocido haga lo que quiera contigo?",
   "For what price would you let a stranger do whatever they want with you?",
   "Por qual preço você deixaria um estranho fazer o que quiser com você?",
   ("Diez mil dólares","$10,000","Dez mil dólares"),
   ("Cien mil dólares","$100,000","Cem mil dólares"),
   ("Un millón o más","A million or more","Um milhão ou mais"),
   ("Mi dignidad no tiene precio","My dignity is priceless","Minha dignidade não tem preço")),
  ("¿Recuerdas la primera vez que te sentiste excitado/a?",
   "Do you remember the first time you felt aroused?",
   "Você se lembra da primeira vez que se sentiu excitado/a?",
   ("A los 12","At 12","Aos 12"),
   ("A los 13","At 13","Aos 13"),
   ("A los 14","At 14","Aos 14"),
   ("A los 15","At 15","Aos 15")),
  ("¿Donde te gustaría recibir un masaje?",
   "Where would you like to receive a massage?",
   "Onde você gostaria de receber uma massagem?",
   ("Cuello","Neck","Pescoço"),
   ("Espalda","Back","Costas"),
   ("Cola","Butt","Bunda"),
   ("Pies","Feet","Pés")),
  ("¿Qué te gustaría que te hagan mientras conduces?",
   "What would you like done to you while driving?",
   "O que você gostaria que fizessem com você enquanto dirige?",
   ("Una manualidad","A hand job","Uma punheta"),
   ("Una mamada","A blowjob","Uma mamada"),
   ("Que te digan cosas excitantes","Saying exciting things to you","Que te digam coisas excitantes"),
   ("Nada, es peligroso","Nothing, it's dangerous","Nada, é perigoso")),
  ("¿Que es lo más grosero que has dicho follando?",
   "What is the rudest thing you've said during sex?",
   "Qual é a coisa mais grosseira que você já disse durante o sexo?",
   ("Eres mi puta","You're my slut","Você é minha vadia"),
   ("Quiero ser tu perrita","I want to be your bitch","Quero ser sua cachorrinha"),
   ("Quiero tu leche","I want your cum","Quero o seu leite"),
   ("Más duro Arturo","Harder!","Mais forte!")),
  ("¿Cómo sería tu noche en pareja ideal?",
   "What would your ideal night with your partner be like?",
   "Como seria sua noite ideal com seu parceiro?",
   ("Con velas y pétalos de rosas","With candles and rose petals","Com velas e pétalas de rosas"),
   ("Follando bien duro sin parar","Going hard non-stop","Transando bem forte sem parar"),
   ("Viendo películas y teniendo sexo de vez en cuando","Watching movies and having sex occasionally","Assistindo filmes e fazendo sexo de vez em quando"),
   ("Adoptando roles para toda la noche","Role-playing all night","Adotando papéis a noite toda")),
  ("¿Qué piensas de las relaciones abiertas?",
   "What do you think about open relationships?",
   "O que você pensa sobre relacionamentos abertos?",
   ("No es para mi","It's not for me","Não é para mim"),
   ("Me gustaría probar","I'd like to try","Gostaria de experimentar"),
   ("Me da curiosidad","I'm curious about it","Tenho curiosidade"),
   ("Me moriría de celos","I'd die of jealousy","Morreria de ciúme")),
  ("¿Cuando fue la última vez que tuviste un sueño sexual intenso?",
   "When was the last time you had an intense sexual dream?",
   "Quando foi a última vez que você teve um sonho sexual intenso?",
   ("Esta semana","This week","Esta semana"),
   ("El mes pasado","Last month","Mês passado"),
   ("Este año","This year","Este ano"),
   ("Ya ni lo recuerdo","I can't even remember","Já nem me lembro")),
  ("¿Cuánto tiempo crees que podrías estar sin follar?",
   "How long do you think you could go without sex?",
   "Quanto tempo você acha que conseguiria ficar sem fazer sexo?",
   ("Un día","One day","Um dia"),
   ("Una semana","One week","Uma semana"),
   ("Un mes","One month","Um mês"),
   ("Un año","One year","Um ano")),
  ("¿Cuál es el mejor momento del día para hacer el amor?",
   "What is the best time of day to make love?",
   "Qual é o melhor momento do dia para fazer amor?",
   ("A la mañana","In the morning","De manhã"),
   ("A la tarde","In the afternoon","De tarde"),
   ("A la noche","At night","À noite"),
   ("A la madrugada","Late night","De madrugada")),
],
16: [
  ("¿Qué agujero te da más placer?",
   "Which hole gives you the most pleasure?",
   "Qual orifício te dá mais prazer?",
   ("La boca","The mouth","A boca"),
   ("La vagina","The vagina","A vagina"),
   ("El ano","The anus","O ânus"),
   ("Las manos o pies al masturbar","Hands or feet while masturbating","As mãos ou pés ao masturbar")),
  ("¿Antes de estar en pareja tuviste sexo prohibido?¿Con quién?",
   "Before being in a relationship, did you have forbidden sex? With whom?",
   "Antes de estar em um relacionamento, você fez sexo proibido? Com quem?",
   ("Un amigo o amiga","A friend","Um amigo ou amiga"),
   ("Un o una familiar","A family member","Um ou uma familiar"),
   ("Un/a compañero/a de trabajo","A coworker","Um/a colega de trabalho"),
   ("Nunca","Never","Nunca")),
  ("¿Con cuál de estos tienes alguna fantasía?",
   "Which of these do you have a fantasy about?",
   "Com qual destes você tem alguma fantasia?",
   ("Un o una policía","A police officer","Um/a policial"),
   ("Un sacerdote o monja","A priest or nun","Um padre ou freira"),
   ("Un/a médico/a","A doctor","Um/a médico/a"),
   ("Otros","Others","Outros")),
  ("¿Quién es tu permitido sexual?",
   "Who is your sexual free pass?",
   "Quem é o seu passe livre sexual?",
   ("Un músico o música","A musician","Um/a músico/a"),
   ("Actor o actriz de cine","A movie actor or actress","Ator ou atriz de cinema"),
   ("Un/a político/a que admiras","A politician you admire","Um/a político/a que você admira"),
   ("Un/a atleta de élite","An elite athlete","Um/a atleta de elite")),
  ("¿Alguna vez comiste mientras follabas?",
   "Have you ever eaten while having sex?",
   "Você já comeu enquanto fazia sexo?",
   ("Fresas","Strawberries","Morangos"),
   ("Chocolate","Chocolate","Chocolate"),
   ("Sushi","Sushi","Sushi"),
   ("Nunca lo hice, lo hacemos la próxima vez","I've never done it, let's do it next time","Nunca fiz, vamos fazer da próxima vez")),
  ("¿Cuántas veces tienes que follar con una persona para contarle lo que te gusta?",
   "How many times do you have to sleep with someone before telling them what you like?",
   "Quantas vezes você precisa fazer sexo com alguém antes de contar o que gosta?",
   ("A la primera","The first time","Na primeira vez"),
   ("Dos o tres veces","Two or three times","Duas ou três vezes"),
   ("Cuatro a siete veces","Four to seven times","Quatro a sete vezes"),
   ("Necesito una relación larga para entrar en confianza","I need a long relationship to feel comfortable","Preciso de um relacionamento longo para ter confiança")),
  ("Cual es la mayor cantidad de veces seguidas que lo has hecho",
   "What is the most times in a row you've done it?",
   "Qual é a maior quantidade de vezes seguidas que você fez?",
   ("Dos","Two","Duas"),
   ("Tres","Three","Três"),
   ("Cuatro","Four","Quatro"),
   ("Cinco o más","Five or more","Cinco ou mais")),
  ("¿Luces prendidas o apagadas?",
   "Lights on or off?",
   "Luzes acesas ou apagadas?",
   ("Prendidas, que se vea TODO","On, so we can see EVERYTHING","Acesas, para ver TUDO"),
   ("Apagadas, me da verguenza","Off, I'm embarrassed","Apagadas, tenho vergonha"),
   ("Tenues, como la luz de las velas","Dim, like candlelight","Tênues, como a luz de velas"),
   ("Luces de colores cómo si fuera un show","Colored lights like a show","Luzes coloridas como um show")),
  ("¿Qué prefieres entre estas opciones?",
   "What do you prefer among these options?",
   "O que você prefere entre estas opções?",
   ("Lamer","Lick","Lamber"),
   ("Morder","Bite","Morder"),
   ("Masajear","Massage","Massagear"),
   ("Escupir","Spit","Cuspir")),
  ("¿Has enviado fotos de alguna de estas partes de tu cuerpo?",
   "Have you sent photos of any of these body parts?",
   "Você já enviou fotos de alguma destas partes do seu corpo?",
   ("Cola","Butt","Bunda"),
   ("Pechos","Breasts","Peitos"),
   ("Partes íntimas","Intimate parts","Partes íntimas"),
   ("Todas las anteriores","All of the above","Todas as anteriores")),
  ("¿Te gusta la lectura erótica?",
   "Do you enjoy erotic reading?",
   "Você gosta de leitura erótica?",
   ("Sólo un mensaje de vez en cuando","Just a message every now and then","Só uma mensagem de vez em quando"),
   ("Me gusta que mi pareja me excite con mensajes siempre que no la puedo ver","I like my partner to excite me with messages when I can't see them","Gosto que meu parceiro me excite com mensagens quando não posso vê-lo"),
   ("Leo novelas enteras","I read entire novels","Leio romances inteiros"),
   ("No me gusta","I don't like it","Não gosto")),
  ("¿Qué tipo de porno te gusta más?",
   "What type of porn do you like most?",
   "Que tipo de pornô você mais gosta?",
   ("Amateur","Amateur","Amador"),
   ("Interracial","Interracial","Interracial"),
   ("Orgías","Orgies","Orgias"),
   ("Sadomasoquismo","Sadomasochism","Sadomasoquismo")),
],
}

# ─── HELPERS ─────────────────────────────────────────────────────────────────

def xml_escape(s):
    return (s.replace("&","&amp;")
             .replace("<","&lt;")
             .replace(">","&gt;")
             .replace("'","\\'")
             .replace('"',"&quot;"))

def key(pack, q, a=None):
    if a is None:
        return f"q_p{pack}_q{q+1}"
    return f"q_p{pack}_q{q+1}_a{a+1}"

# ─── BUILD XML BLOCKS ────────────────────────────────────────────────────────

def build_xml_entries(locale_idx):
    lines = []
    for pack_id in range(1, 17):
        lines.append(f"\n    <!-- Pack {pack_id} -->")
        for qi, row in enumerate(PACKS[pack_id]):
            q_text = xml_escape(row[locale_idx])
            lines.append(f'    <string name="{key(pack_id,qi)}">{q_text}</string>')
            for ai in range(4):
                a_text = xml_escape(row[3 + ai][locale_idx])
                lines.append(f'    <string name="{key(pack_id,qi,ai)}">{a_text}</string>')
    return "\n".join(lines)

# locale indices: 0=ES 1=EN 2=PT

for locale_idx, locale_dir in [(0,"values"), (1,"values-en"), (2,"values-pt")]:
    path = os.path.join(BASE, locale_dir, "strings.xml")
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    # Insert before </resources>
    insertion = build_xml_entries(locale_idx)
    new_content = content.replace("</resources>", insertion + "\n</resources>")
    with open(path, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Updated {locale_dir}/strings.xml")

# ─── BUILD QuestionBank.kt (resource IDs) ────────────────────────────────────

kt_lines = [
    "package com.idea3d.juegoparaparejas",
    "",
    "data class QuestionItem(val questionRes: Int, val answerRes: List<Int>)",
    "",
    "data class QuestionPack(val id: Int, val questions: List<QuestionItem>) {",
    "    fun questionAt(index: Int): QuestionItem = questions[index]",
    "    val size: Int get() = questions.size",
    "}",
    "",
    "object QuestionBank {",
    "    val packs: Map<Int, QuestionPack> = mapOf(",
]

for pack_id in range(1, 17):
    kt_lines.append(f"        {pack_id} to QuestionPack({pack_id}, listOf(")
    for qi in range(len(PACKS[pack_id])):
        q_res = f"R.string.{key(pack_id,qi)}"
        a_res = ", ".join(f"R.string.{key(pack_id,qi,ai)}" for ai in range(4))
        kt_lines.append(f"            QuestionItem({q_res}, listOf({a_res})),")
    kt_lines.append("        )),")

kt_lines += [
    "    )",
    "",
    "    fun getPack(id: Int): QuestionPack = packs[id] ?: error(\"Unknown pack id: $id\")",
    "}",
    "",
]

qb_path = "/Users/nestor/Juego-para-parejas/app/src/main/java/com/idea3d/juegoparaparejas/QuestionBank.kt"
with open(qb_path, "w", encoding="utf-8") as f:
    f.write("\n".join(kt_lines))
print("Updated QuestionBank.kt")

